mongodb/mongo-rust-driver

src/client/auth/mod.rs
src/client/executor.rs
src/client/options/mod.rs
src/cmap/establish/handshake.rs
src/coll/mod.rs
src/operation/aggregate/test.rs
src/operation/distinct/test.rs
src/operation/find/test.rs
src/operation/find_and_modify/test.rs
src/operation/get_more/test.rs
src/operation/list_databases/test.rs
src/options.rs
src/sdam/state/mod.rs
src/selection_criteria.rs
src/test/spec/connection_stepdown.rs
src/test/spec/initial_dns_seedlist_discovery.rs

clippy got an update in rust 1.40 and started failing on the codebase, and this PR fixes those failures.

minor: fix 1.40 clippy failures

---

src/bson_util.rs
src/coll/batch.rs
src/coll/mod.rs
src/error.rs
src/results.rs
src/test/coll.rs

[RUST-246](https://jira.mongodb.org/browse/RUST-246)
This PR adds batching to `insert_many`, which breaks up inserts that would be too large for a single command into several, combining their errors and results as they come back from the server.
This was originally #105 , but due to some GitHub sync issues with my fork once this repo became public, I had to re-open.

RUST-246 Batch large inserts

---

src/db/options.rs

I am trying to port r2d2-mongodb to use this new mongodb driver and it would be very nice if DatabaseOptions could be cloned.

Derive Clone for DatabaseOptions

---

.evergreen/install-dependencies.sh
.evergreen/run-tests.sh

This PR updates our evergreen config to use a [cargo option](https://github.com/rust-lang/cargo/issues/2078#issuecomment-434388584) (via an environment variable) which forces cargo to use the git cli to fetch the crates index rather than libgit2, allowing us to sidestep the issues we were having with the ssh-agent on macOS.

minor: fix macOS evergreen failures

---

src/coll/options.rs

So it'll throw a not very helpful error at you:
> error[E0599]: no method named `build` found for type `mongodb::coll::options::TypedBuilder_BuilderFor_ReplaceOptions<(), (std::option::Option<bool>,), (), (), ()>` in the current scope

Default on ReplaceOptions.hint is missing

---

src/client/mod.rs
src/error.rs
src/sdam/description/server.rs
src/sdam/description/topology/server_selection/mod.rs
src/sdam/public.rs
src/test/client.rs
src/test/util/mod.rs

[RUST-268](https://jira.mongodb.org/browse/RUST-268)
This PR improves the server selection timeout error messages by mentioning why the timeout ocurred as well as the state of the topology. It's loosely based off of the [error message psuedocode in the server selection spec](https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst#server-selection-errors). 
The formatting and content are also inspired by similar error messages in the [go driver](https://github.com/mongodb/mongo-go-driver/pull/148):
```
Error { kind: ServerSelectionError { message: "Server selection timeout: No servers suitable for criteria ReadPreference(Secondary { tag_sets: Some([{\"asdfasdf\": \"asdfadsf\"}]), max_staleness: None }). Current topology: { Type: Unknown, Servers: …
```

RUST-268 Improve server selection timeout error messages

---

src/coll/options.rs

Adds the sort option to `FindOneOptions`. Unclear if a specific test is needed.

add Sort option to FindOneOptions

---

README.md

It is necessary as it is using afterwards

 Added "Bson" in the scope of " Finding documents in a collection" in README

---

README.md

This PR fixes some typos in the README that I found while reviewing it again.

minor: fix typos in README

---

Cargo.toml
README.md
src/test/spec/connection_stepdown.rs
src/test/spec/initial_dns_seedlist_discovery.rs

This PR removes the dependency on the third party `assert_matches` crate in favor of using the newly introduced `matches!` in Rust 1.42

minor: remove dev dependency on assert_matches

---

src/client/options/mod.rs
src/runtime/mod.rs
src/runtime/stream.rs

This is a follow up PR for [RUST-300](https://jira.mongodb.org/browse/RUST-300)
This previous PR (#149) only updated the SRV/TXT DNS resolution to be async. This PR updates the regular DNS resolution to also be async by replacing the usage of `std::net::ToSocketAddrs` with the async-std/tokio equivalents.

RUST-300 Update StreamAddress resolution to be async

---

README.md

The README hadn't been updated to the latest patch release.

minor: update driver version in README.md

---

src/client/executor.rs
src/concern/mod.rs
src/concern/test.rs
src/db/mod.rs
src/operation/aggregate/mod.rs
src/operation/create/mod.rs
src/operation/delete/mod.rs
src/operation/drop_collection/mod.rs
src/operation/drop_database/mod.rs
src/operation/find_and_modify/mod.rs
src/operation/insert/mod.rs
src/operation/mod.rs
src/operation/run_command/mod.rs
src/operation/run_command/test.rs
src/operation/update/mod.rs
src/sdam/description/topology/mod.rs

This breaks off some changes from the implicit sessions PR to reduce the size of the diff. This PR adds support for determining if an operation is acknowledged (RUST-289) and fixes a bug where $readPreference wasn't being set against certain topologies (RUST-397).

Read preference and write concern changes from implicit sessions PR

---

README.md

[RUST-328](https://jira.mongodb.org/browse/RUST-328)
This PR updates the README to include examples of using the async API. It also includes instructions for selecting a runtime or enabling the sync API.

RUST-328 Update the README to include async examples

---

Cargo.toml
src/lib.rs
src/sync/mod.rs

With a bit of work, I was able to spin up a [local instance of docs.rs](https://github.com/rust-lang/docs.rs/blob/master/README.md#cli) to verify that this generates the sync API documentation. To see the generated documentation locally without needing to set up a docs.rs instance, you can run `cargo rustdoc -p mongodb --open -- --cfg docsrs`.

RUST-408 Generate API documentation for the sync API on docs.rs

---

src/client/executor.rs
src/operation/mod.rs
src/operation/run_command/mod.rs
src/test/client.rs

[RUST-396](https://jira.mongodb.org/browse/RUST-396)
This PR updates `run_command` to parse command errors from server responses and return them as `Error` rather than as part of the command response.
e.g.
```rust
// before
db.run_command(doc! { "asdfaf": true }, None).await; // Ok(Document({ "ok": 0, ... })
// after
db.run_command(doc! { "asdfaf": true }, None).await; // Err(ErrorKind::CommandError { ... })
```
Without this logic, it can be easy to ignore errors unintentionally, as is seen in the test fix included in this PR.
For completeness, I redid my survey of the other drivers, and there does not appear to be a consensus on this behavior:
- libmongoc - validates
- CXX - validates
- Swift - validates
- PHP - validates
- Ruby - result that can be validated by user
- Go - result that …

RUST-396 Parse responses with command errors into Errors in run_command

---

src/client/executor.rs
src/error.rs
src/operation/drop_collection/mod.rs
src/operation/mod.rs
src/test/coll.rs

[RUST-392](https://jira.mongodb.org/browse/RUST-392)
This PR updates `Collection::drop` to ignore errors returned from the server when dropping a nonexistent collection.

RUST-392 Suppress "ns not found" errors

---

src/client/options/mod.rs
src/client/options/test.rs
src/concern/mod.rs
src/operation/aggregate/test.rs
src/operation/count/test.rs
src/operation/find/test.rs
src/test/spec/read_write_concern/connection_string.rs

[RUST-434](https://jira.mongodb.org/browse/RUST-434)
This PR reimplements a read concern as a struct (`ReadConcern`) with a single field `level` (`ReadConcernLevel` enum) both to better match with the spec and to allow for future compatibility. It also fixes a bug where every read concern parsed from a URI was being initialized as a `ReadConcernLevel::Custom`.

RUST-434 Rewrite ReadConcern as struct

---

src/coll/options.rs

This removes the unused `IndexModel` struct. It can be reintroduced when the index management specification is implemented.

minor: remove unused IndexModel struct

---

src/client/executor.rs
src/client/session/test.rs
src/cmap/background.rs
src/cmap/establish/handshake/mod.rs
src/event/cmap.rs
src/event/command.rs
src/lib.rs
src/operation/aggregate/mod.rs
src/operation/count/mod.rs
src/operation/create/mod.rs
src/operation/delete/mod.rs
src/operation/distinct/mod.rs
src/operation/drop_collection/mod.rs
src/operation/drop_database/mod.rs
src/operation/find/mod.rs
src/operation/find_and_modify/mod.rs
src/operation/find_and_modify/test.rs
src/operation/get_more/mod.rs
src/operation/insert/mod.rs
src/operation/list_collections/mod.rs
src/operation/list_databases/mod.rs
src/operation/run_command/mod.rs
src/operation/update/mod.rs
src/sdam/monitor.rs
src/sdam/state/mod.rs
src/test/cursor.rs
src/test/spec/connection_stepdown.rs
src/test/spec/runner/operation.rs

It appears that we accidentally never removed the project-wide annotation to suppress unused variable warnings, so I removed it and fixed all the issues. Fortunately, almost all of these were not indicators of bugs; the one exception was a very minor bug in handshake metadata logic for libraries wrapping the driver, where we accidentally appended the platform name to the driver's version string instead of the platform string (but with the proper delimiter, so this likely didn't break anything).

minor: remove unused variables

---

src/coll/options.rs
src/operation/find_and_modify/options.rs
src/operation/find_and_modify/test.rs

Added a hint option to findAndModify operation (similar to the find operation) and tested its use in the delete, replace and update operations

RUST-362 Add hint option to findAndModify operations

---

src/error.rs
src/operation/delete/test.rs
src/operation/insert/test.rs
src/operation/update/test.rs
src/test/coll.rs

This PR introduces a new field errInfo in WriteConcernError and tests verifies that the provenance field is propagated from the server to the client

RUST-370 Ensuring that the WriteConcernError errInfo object is propagated

---

src/client/options/mod.rs
src/test/spec/auth.rs
src/test/spec/json/auth/connection-string.json
src/test/spec/json/auth/connection-string.yml
src/test/spec/json/auth/mongodb-aws.rst

[RUST-479](https://jira.mongodb.org/browse/RUST-479)
This was the original ticket I planned on completing. It relaxes the connection string parsing logic to allow authSource to be specified without attempting to authenticate.
[RUST-502](https://jira.mongodb.org/browse/RUST-502)
This was another ticket dealing with authSource whose tests I pulled in while syncing. It was easier to just implement this behavior rather than adding logic to skip it, so I included it as part of this PR.
I also included the sync commits in this PR, because otherwise the waterfall would start being red until I merged this PR.

RUST-479 / RUST-502 Improve authSource handling

---

README.md
src/client/options/mod.rs
src/runtime/resolver.rs
src/sdam/srv_polling/mod.rs
src/srv.rs
src/test/atlas_connectivity.rs

RUST-483
This PR allows users to resolve `mongodb+srv` connection strings using alternate DNS resolver configurations. This helps users avoid the [known performance issue in trust-dns-resolver on Windows](https://github.com/bluejekyll/trust-dns#resolver) when using the system configuration (issue seen in RUST-467).
I opted to only include a helper on `ClientOptions` and not one on `Client` itself since this seemed like a very specific issue that was strictly configuration related.

RUST-483 Allow alternate DNS resolver configs

---

src/client/auth/mod.rs

I realized right after merging RUST-359 that I forgot to make the change that was the whole reason we delayed merging it in the first place, so here it is

minor: make AuthMechanism non-exhaustive

---

src/client/auth/aws.rs
src/test/spec/mod.rs

To prevent the changes in RUST-511 from breaking the tests, this PR updates the constraint in `run_spec_test` to use `DeserializedOwned`.
This also fixes a compilation issue with the driver in older versions of Rust.

RUST-511 Remove unnecessary usage of Deserialize<'de>

---

src/client/auth/mod.rs
src/collation.rs
src/error.rs
src/results.rs

https://jira.mongodb.org/browse/RUST-524
This PR marks structs to which we anticipate adding fields as `non_exhaustive`.

RUST-524 mark structs non_exhaustive

---

README.md

The latest version of the driver is 1.1.1 but the readme says it is 1.1.0

Update Cargo version in main readme

---

src/test/documentation_examples.rs
src/test/mod.rs

The examples for us to implement are given in [this comment*](https://jira.mongodb.org/browse/DRIVERS-356?focusedCommentId=1521532&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1521532) on the DRIVERS ticket. The examples themselves are rendered in the various subpages of [this tutorial](https://docs.mongodb.com/manual/crud/), which has separate tabs for viewing the examples in each driver's language. I heavily followed [my footsteps](https://github.com/mongodb/mongo-cxx-driver/commit/201505d7bfbb9e3e7509340bcd8a9c006bb0000a) from my carefree youth when I was on the C++ driver, including making these examples a test that can be executing to ensure that the examples were written correctly. (Ironically, the C++ examples don't seem to have ever been added to …

RUST-539 Create CRUD examples for documentation

---

.evergreen/config.yml

RUST-549
This PR increases the ulimit to 64000 before starting orchestration or any tests to prevent the "too many open files" test failures we see on async-std with macOS. They seem to be caused by EVG-13244, so this change will not be necessary at some point in the future. Until then, I think it's worth manually setting the ulimit to avoid test failures.

RUST-549 Increase ulimit in evergreen tests

---

src/coll/mod.rs
src/coll/options.rs
src/operation/aggregate/mod.rs
src/operation/count_documents/mod.rs
src/operation/count_documents/test.rs
src/operation/mod.rs
src/test/coll.rs

RUST-576
This PR fixes a bug where `count_documents` would return an error if called on a client that had a write concern set. This only applies to 3.6 servers it seems (I only tested with 4.4 and 3.6, did not apply to 4.4).

RUST-576 Fix count_documents fails when writeConcern set on Collection

---

README.md

This PR adds a note to the README informing users of some workarounds for https://github.com/rust-lang/rust/issues/75992, which is often encountered when using the driver in combination with actix-web.

minor: suggest workarounds for rustc 1.46+ regression

---

src/client/mod.rs
src/operation/aggregate/test.rs
src/operation/count/test.rs
src/operation/distinct/test.rs
src/operation/find/test.rs
src/results.rs
src/test/spec/unified_runner/operation.rs

Rust 1.48 came out today, and as usual there are a host of new lints

minor: fix lints for rust 1.48

---

src/cmap/establish/handshake/mod.rs
src/cmap/establish/handshake/test.rs
src/cmap/establish/mod.rs
src/cmap/establish/test.rs
src/cmap/mod.rs
src/sdam/monitor.rs

RUST-598
This fixes a bug where monitoring connections didn't perform the MongoDB handshake as part of establishing their connections. I decided to break this off from the other connection storms work since it seemed to be ready and the other stuff is still waiting on spec changes.

RUST-598 Perform handshake when establishing monitoring connections

---

src/cmap/test/file.rs
src/cmap/test/mod.rs
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-maxConnecting-is-enforced.json
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-maxConnecting-is-enforced.yml

RUST-609
This PR pulls in the latest version of the "maxConnecting is enforced" spec test, hopefully fixing some intermittent failures we were seeing with it. In order to run the new version of the test, I had to update our CMAP test operations to be dispatched in order that they are listed in the file (see the first commit). This latter change fixes RUST-608.
This PR is part of the "Avoiding Connection Storms" work (DRIVERS-781).

RUST-609 Fix flaky maxConnecting test

---

src/sdam/monitor.rs
src/sdam/test.rs
src/test/auth_aws.rs

RUST-610
This PR implements a new SDAM spec prose test that ensures the monitors wait at least 500ms between failed checks. This is part of the Avoiding Connection Storms project (DRIVERS-781).
relevant spec change: https://github.com/mongodb/specifications/commit/6c5b2acbf5a30b2c79e904532d51ba9ed8783247

RUST-610 Test that monitors wait at least minHeartbeatFrequencyMS between failed checks

---

Cargo.toml
src/cmap/establish/handshake/mod.rs

When running this library on alpine I received the error 
```
os_info::imp::lsb_release lsb_release command failed with Os { 
code: 2, kind: NotFound, message: "No such file or directory" 
}
```
I think this has been fixed in a later version of os_info
https://github.com/stanislav-tkach/os_info/commit/602ff91f0904a4673a96f56fe79fb8a46222fa72  
This patch up grades os-info to 3.0.1

RUST-623 Upgrade os_info to 3.0.1

---

src/client/options/mod.rs
src/cmap/options.rs
src/test/spec/unified_runner/test_file.rs
src/test/util/event.rs

In preparation of releasing the alpha, hide the not-yet-complete versioned API implementation from the public API.

minor: hide versioned API from public API

---

.evergreen/config.yml
README.md

This PR updates the README to indicate that 1.45 is the MSRV for the master branch and the 2.0.0-alpha. This is required since `tokio-util`'s MSRV is 1.45. This PR also updates the evergreen config to test this properly.

minor: bump minimum supported Rust version to 1.45

---

Cargo.toml

The BSON crate offered the "unsigned integer to integer (u2i)" auto conversion feature. Since the crate is now reexported, it would be nice to still be able to use this.

Added optional bson u2i feature

---

src/client/mod.rs

RUST-675
This PR eliminates a race in server selection between a task subscribing to topology updates and the update actually occurring. Right now, a client only subscribes to server selection updates after it fails to select a server, so if the topology becomes selectable while a server selection attempt is in progress but before it fails, the client will never know about the update since it will only have started listening for it after the update already happened, leading to a server selection timeout. This PR updates the server selection loop to subscribe to topology updates _before_ it attempts to select a server, preventing this error from occurring.

RUST-675 eliminate race in server selection

---

README.md

This PR updates the warning to reflect the current state of affairs, notably that the issue doesn't seem to be present in 1.48 and that it does not affect 1.0, 1.2, or 2.0.0-alpha.

minor: update Rust regression warning in README

---

src/error.rs

These arrays aren't modified in run time, so there's no reason for them to be vectors.

RUST-681 Replace lazy static vectors with constant arrays

---

src/test/spec/command_monitoring/operation.rs
src/test/spec/runner/operation.rs

This resolves warnings while running tests.

Remove redundant semicolons

---

.evergreen/config.yml
Cargo.toml
README.md
src/client/auth/mod.rs
src/client/auth/scram.rs

This PR leaves PBKDF2 at 0.6 instead of 0.7 to avoid bumping MSRV to 1.47.

RUST-682 Update encryption dependencies

---

src/client/session/test.rs
src/cmap/test/integration.rs
src/cmap/test/mod.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/sdam/test.rs
src/test/client.rs
src/test/coll.rs
src/test/spec/command_monitoring/mod.rs
src/test/spec/connection_stepdown.rs
src/test/spec/retryable_writes/mod.rs
src/test/spec/unified_runner/entity.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_file.rs
src/test/spec/unified_runner/test_runner.rs
src/test/spec/v2_runner/mod.rs
src/test/spec/v2_runner/test_file.rs
src/test/util/event.rs
src/test/util/failpoint.rs
src/test/util/mod.rs

RUST-604
This PR updates the unified runner to use regular `mongodb::Client` for the client entities instead of `EventClient` / `TestClient`, which allows us to unconditionally use `buildInfo` and drop the `collect_server_info` option in `TestClient`.

RUST-604 Use mongodb::Client for unified runner entities

---

src/client/executor.rs
src/sdam/state/mod.rs
src/test/spec/retryable_reads.rs

This PR adds a test to ensure deadlock doesn't occur during a retry when all connections are checked out from the pool. This was possible in the released 2.0.0-alpha, but was incidentally fixed in a subsequent PR.

RUST-714 Fix possible deadlock during retry

---

src/client/executor.rs
src/test/spec/retryable_reads.rs

RUST-714
This backports a fix for a potential deadlock that can occur during a retry when all connections are checked out from the pool.

RUST-714 Fix possible deadlock during retry (1.x driver)

---

.evergreen/config.yml
README.md

A transitive dependency of async-std bumped their MSRV to 1.46, so we must do so too. This PR also updates the README for the 1.2.x branch to only reflect the MSRV of the 1.2.x driver. This should help reduce any stale information across READMEs. I'll file a similar PR to update the master branch to only include the latest released version and the master requirement.

minor: bump MSRV to 1.46 (1.2.x)

---

README.md

This PR removes past version MSRV information from the master branch README. Note that since we tag all our major and minor releases on the master branch, the README used by crates.io for a given release will continue to display the correct MSRV for that version, even if master has moved forwards afterwards.
Including only a single version will help reduce the proliferation of stale MSRV information for different releases (e.g. the [requirements section in the 2.0.0-alpha release](https://crates.io/crates/mongodb/2.0.0-alpha) has outdated MSRV information for the master branch).  Subsequent patch releases on the version branch then only have to update the MSRV in that branch's README, rather than having to update it in master / other release branches as well. 
Note that the MSRV for the …

minor: only include master branch's MSRV in README

---

src/client/options/mod.rs

RUST-724
This updates the `versioned-api` branch to include the versioned API options in the public API for private beta users to use. We'll need to do this on the master branch in the future, so I filed RUST-732 to track that.

RUST-724 Include versioned API options in the public API

---

.evergreen/aws-ecs-test/src/main.rs
README.md
src/client/mod.rs
src/client/session/test.rs
src/coll/mod.rs
src/cursor/mod.rs
src/cursor/session.rs
src/db/mod.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/sync/client.rs
src/sync/coll.rs
src/sync/cursor.rs
src/sync/db.rs
src/sync/test.rs
src/test/atlas_connectivity.rs
src/test/auth_aws.rs
src/test/client.rs
src/test/coll.rs
src/test/documentation_examples.rs
src/test/util/mod.rs
tests/readme_examples.rs

RUST-735
This PR removes `Document` as the default generic type for `Collection` and `Cursor` and updates `Database::collection` and `Database::collection_with_options` to return `Collection<T>`. As part of this, the existing typed helpers became redundant and were removed. These changes were made to ease and promote the use of serde models with the driver instead of regular Documents.
Note: I didn't update the README examples to avoid confusing users of the 1.2.x or 2.0.0-alpha versions. I filed RUST-736 to cover the work for updating that, which we can do right before the release.

RUST-735 Remove Document as default generic type on Collection and Cursor

---

src/coll/options.rs
src/test/coll.rs

Most of our options structs include the `serde_with::skip_serializing_none` attribute to avoid sending null values to the server for unspecified options. We don't include this attribute on `DropCollectionOptions`, which means that if a user specifies `None` for `write_concern`, the server will return a TypeMismatch error. It's likely that this hasn't been encountered since `write_concern` is the only field in `DropCollectionOptions`, so users would likely just omit the options completely rather than specifying `None`; however, we should still fix this to avoid unnecessary errors.

RUST-759 Skip serializing None for DropCollectionOptions

---

Cargo.toml
src/cursor/mod.rs
src/error.rs
src/sdam/description/server.rs

RUST-738
Now that the BSON errors are `Clone`, we can remove the `Arc` wrapper around them in `ErrorKind`. To bring in these changes, this PR also updates the `Cargo.toml` to track the master branch of `bson-rust`.

RUST-738 Remove Arc wrapper around BSON errors

---

src/bson_util/mod.rs
src/client/mod.rs
src/db/mod.rs
src/db/options.rs
src/operation/create/test.rs
src/operation/list_databases/mod.rs
src/operation/list_databases/test.rs
src/results.rs
src/sync/client.rs
src/sync/db.rs
src/test/client.rs
src/test/db.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/v2_runner/operation.rs

RUST-740
This PR updates `Client::list_databases` and `Database::list_collections` to return structs that implement `Deserialize` rather than just `Document`.

RUST-740 Return Deserialize structs from list_databases and list_collections

---

src/coll/mod.rs
src/runtime/mod.rs
src/sync/coll.rs
src/sync/cursor.rs
src/sync/db.rs
src/sync/test.rs
src/test/coll.rs

RUST-754
This PR updates the various insert and replace methods to accept `impl Borrow<T>`, which means that both owned values and values that can be converted into references can be accepted in these methods. 
In a related change, the trait requirements on `T` in the sync driver were relaxed now that tokio and async-std's blocking functions no longer require it.

RUST-754 Accept impl Borrow<T> in insert and replace methods

---

src/bson_util/mod.rs
src/client/options/mod.rs
src/coll/mod.rs
src/coll/options.rs
src/concern/mod.rs
src/db/options.rs
src/operation/count/mod.rs
src/operation/count_documents/mod.rs
src/operation/mod.rs
src/operation/update/mod.rs
src/results.rs
src/sync/coll.rs
src/test/spec/command_monitoring/operation.rs
src/test/spec/crud_v1/count.rs
src/test/spec/crud_v1/delete_many.rs
src/test/spec/crud_v1/delete_one.rs
src/test/spec/crud_v1/find.rs
src/test/spec/crud_v1/replace_one.rs
src/test/spec/crud_v1/update_many.rs
src/test/spec/crud_v1/update_one.rs
src/test/spec/read_write_concern/document.rs

RUST-764
This updates a number of results and options in the driver that current use signed integers where unsigned integers could be used instead, since the values stored there will always be positive.

RUST-764 Use unsigned integers for values that should always be non-negative

---

src/client/options/mod.rs
src/cmap/connection_requester.rs
src/cmap/mod.rs
src/cmap/options.rs
src/cmap/test/file.rs
src/cmap/test/mod.rs
src/error.rs
src/event/cmap.rs

RUST-757
This PR removes the `wait_queue_timeout` option from `ClientOptions`, since it will be superseded by the general `timeoutMS` option from the Client Side Operations Timeout specification.
In the meantime, users can just use the timeout functionality from their respective runtimes as a workaround.
e.g. for tokio:
```rust
tokio::time::timeout(Duration::from_secs(5), coll.insert_one(doc! { "x": 1 }, None)).await?;
```
Note this may lead to some connection churn, but it seems to be an acceptable alternative for now.

RUST-757 Remove `wait_queue_timeout` option

---

src/coll/mod.rs
src/cursor/mod.rs
src/cursor/session.rs
src/db/mod.rs
src/lib.rs
src/sync/cursor.rs
src/sync/mod.rs
src/test/cursor.rs
src/test/spec/v2_runner/operation.rs

RUST-796
This PR adds a `SessionCursor::next(&mut ClientSession)` method to allow for iteration of the cursor that allows for easy reborrowing of the session. As part of this, `SessionCursor::with_session` was renamed to `SessionCursor::stream` to more accurately reflect its intent now that `next` is around. Similar changes were made for the sync driver.
I also went ahead and updated the documentation for cursors in general to be a little more straightforward.

RUST-796 Provide easy way to reborrow session in between cursor iterations

---

src/cmap/mod.rs
src/cmap/options.rs

RUST-823
This PR updates the default `max_pool_size` to 10. For some background on the motivation, see [here](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing) and [here](https://kwahome.medium.com/database-connections-less-is-more-86c406b6fad). Note that this is also in line with the defaults for [`r2d2`](https://docs.rs/r2d2/0.8.9/r2d2/struct.Builder.html#method.max_size) and [`bb8`](https://docs.rs/bb8/0.7.0/bb8/struct.Builder.html#method.max_size).

RUST-823 Reduce default `max_pool_size` to 10

---

Cargo.toml
src/bson_util/mod.rs
src/sdam/description/server.rs
src/sdam/description/topology/server_selection/test/mod.rs

RUST-811
This update the driver to accommodate the new `"chrono-0_4"` and `"uuid-0_8"` feature flags added to the bson library in https://github.com/mongodb/bson-rust/pull/258.

RUST-811 Introduce feature flags for `chrono` and `uuid` interop

---

.evergreen/config.yml

RUST-162 / RUST-814
This PR updates our evergreen configuration to run on Ubuntu 18.04 ARM64, Ubuntu 18.04, and Ubuntu 20.04, and it removes testing on Ubuntu 16.04.
I also introduced the concept of "bang builds" (i.e. required builds) by adding an exclamation point in front of the more important variants. This will automatically sort them to the top of the waterfall / a patch view and can help for easy differentiation from the other, less important tasks. I borrowed this idea from the server's [evergreen config](https://evergreen.mongodb.com/waterfall/mongodb-mongo-master). I propose that we limit the tasks scheduled as part of a PR to just the bang builds and have the waterfall take care of running the other tasks, especially now that we have more variants. This should help cut back on …

RUST-162 / RUST-814 Update evergreen test variants

---

src/client/options/mod.rs
src/sdam/srv_polling/mod.rs
src/sdam/srv_polling/test.rs
src/sdam/state/mod.rs
src/srv.rs
src/test/spec/initial_dns_seedlist_discovery.rs

RUST-571
The initial dns seedlist tests were pretty flaky, and I believe for (at least) these 3 reasons:
- the test lock was not acquired before running it
- we don't have SDAM monitoring yet, so our checking of the discovered hosts was racy
- there was a race between SRV polling and discovery of an Unknown topology
- We were not waiting before doing the first SRV poll after client creation, so the SRV pol could update the topology before the monitors had a chance to mark it as a replica set, causing the polling and SDAM to get into a loop of updating the topology back and forth
This PR fixes these three issues, though sadly it appears that we [still have failures in this test](https://evergreen.mongodb.com/task/mongo_rust_driver_tests__async_runtime~tokio_auth_and_tls~auth_and_tls_os~maco …

RUST-571 Fix race between SDAM discovery and SRV polling

---

src/client/auth/mod.rs
src/client/options/mod.rs
src/cmap/establish/handshake/mod.rs
src/cmap/mod.rs
src/cmap/test/mod.rs
src/coll/options.rs
src/test/spec/unified_runner/mod.rs
src/test/util/event.rs
src/test/util/matchable.rs

RUST-847
This PR redacts the debug output for `Credential` to just `Credential("REDACTED")` in the 1.2.x driver. I opted to include a redacted implementation rather than omit one so that the `Credential` struct is more easily usable in structs that are `Debug`. This also does allow some amount of debugging of it via print statements in that you can tell one is present in an options struct.
This fixes the security issue reported as part of RUST-591 for the 1.2.x driver. The issue was already resolved in the 2.0.0-beta release of the driver.

RUST-847 Redact `Credential` `Debug` output (1.2.x)

---

src/cmap/options.rs
src/cmap/test/mod.rs
src/event/cmap.rs

RUST-849
This PR removes the fields from the `ConnectionPoolOptions` that are included in CMAP events that are not mandated by the CMAP specification. This will protect us from accidentally leaking any sensitive information from these events in the future (e.g. from `TlsOptions`).

RUST-849 Remove extra fields from `ConnectionPoolOptions` included in CMAP events

---

src/collation.rs

Teeny tiny PR!! The new version of `cargo-rustdoc` requires explicit [autolinks](https://spec.commonmark.org/0.27/#autolinks). Just 4 <<angle brackets>> to look at.

minor: fix rustdoc

---

src/bson_util/mod.rs
src/client/auth/mod.rs
src/client/options/mod.rs
src/client/options/test.rs
src/concern/mod.rs
src/selection_criteria.rs

Implemented `Serialize` for `ClientOptions`. It's worth noting that the schema used is specific to the URI Options spec tests, and we currently can't deserialize back into `ClientOptions`.
To make this work, there's a custom implementation of `Serialize` which uses a helper struct to flatten the appropriate nested structs. These nested structs are likewise serialized using the [`serialize_with`](https://serde.rs/field-attrs.html#serialize_with) attribute in order to avoid conflicting serialize implementations.

RUST-310 Use serde for `ClientOptions` tests

---

README.md

I noticed a small typo when I was reading the documentation 😞 
I think this is the right thing to fix? Or should it be the other way around 🤔

minor: fix readme typo

---

src/test/spec/json/unified-runner-examples/poc-sessions.json
src/test/spec/json/unified-runner-examples/poc-sessions.yml
src/test/spec/json/unified-runner-examples/poc-transactions.json
src/test/spec/json/unified-runner-examples/poc-transactions.yml
src/test/spec/unified_runner/entity.rs
src/test/spec/unified_runner/matcher.rs
src/test/spec/unified_runner/mod.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_file.rs
src/test/spec/unified_runner/test_runner.rs
src/test/util/event.rs

As above. Implemented a new unified test runner entity which wraps on a `ClientSession` and on its LSID, so that when the session is dropped, the LSID persists in the entity map to cross-reference with expected events.
Currently skipping one test in `poc-transactions` because it relies on index management, which isn't implemented AFAIK.

RUST-697 / RUST-701 Add sessions and transactions to unified test runner

---

src/coll/options.rs
src/test/spec/json/crud/unified/aggregate-let.json
src/test/spec/json/crud/unified/aggregate-let.yml

RUST-836
This adds support for the 'let' option to `aggregate`.  Unfortunately, `let` is a reserved keyword in Rust, so this PR implements it as `let_vars`.  `r#let` would have worked as well, but that's awkward and unidiomatic (typically raw identifiers are only used for edition compatibility), and could also have caused confusion, as the debug format prints it as just "let".

RUST-836 Support the 'let' option for aggregate

---

src/test/mod.rs
src/test/spec/mod.rs
src/test/spec/unified_runner/test_file.rs
src/test/spec/v2_runner/test_file.rs

RUST-656
This allows the "serverless" entry, but does not set up the evergreen environment for running tests against a serverless deployment; the goal is to unblock other changes that happen to pick up spec test updates with `serverless: forbid`.

RUST-656 Allow "serverless" entry in runOnRequirement

---

src/cmap/options.rs
src/cmap/test/mod.rs
src/cmap/worker.rs
src/test/spec/json/connection-monitoring-and-pooling/README.rst
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-no-idle.json
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-no-idle.yml
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-no-stale.json
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-no-stale.yml
src/test/spec/json/connection-monitoring-and-pooling/pool-clear-min-size.json
src/test/spec/json/connection-monitoring-and-pooling/pool-clear-min-size.yml

This also picks up the changes for RUST-775.

RUST-774 Allow tests to specify `backgroundThreadIntervalMS` to fix a race condition.

---

.evergreen/config.yml
src/cmap/test/integration.rs
src/sdam/test.rs
src/test/mod.rs
src/test/spec/json/connection-monitoring-and-pooling/README.rst
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-maxConnecting-is-enforced.json
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-maxConnecting-is-enforced.yml
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-maxConnecting-timeout.json
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-maxConnecting-timeout.yml
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-returned-connection-maxConnecting.json
src/test/spec/json/connection-monitoring-and-pooling/pool-checkout-returned-connection-maxConnecting.yml

RUST-881
This adds an evergreen test configuration to run tests against a server that requires the API version be set in every call.  A few tests needed to be updated because setting the API version on the client switches from `isMaster` to `hello`.

RUST-881 Run tests with `requireApiVersion: 1`

---

src/test/documentation_examples.rs

RUST-795
The expected format and content for the versioned API connection examples changed a bit since they were initially added; this PR updates them to match.

RUST-795 Update versioned api connection examples

---

src/client/executor.rs
src/client/session/mod.rs
src/cmap/conn/command.rs
src/cmap/establish/test.rs
src/cmap/test/integration.rs
src/coll/mod.rs
src/operation/count/test.rs
src/operation/count_documents/mod.rs
src/operation/count_documents/test.rs
src/sdam/description/topology/mod.rs
src/sdam/state/mod.rs
src/selection_criteria.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/v2_runner/operation.rs

RUST-882
The `From<u64>` impl for `Bson` was recently removed due to it being lossy for certain values. This functionality was relied upon by the driver in a few areas which needed to be updated.

RUST-882 Stop relying on `From<u64>` for `Bson`

---

src/client/options/mod.rs
src/cmap/establish/handshake/test.rs
src/cmap/establish/test.rs
src/cmap/options.rs
src/test/spec/unified_runner/test_file.rs

RUST-732
This approximately reverts the [commit](https://github.com/mongodb/mongo-rust-driver/commit/ffae5c31c6ac368fc0c242c3bcf3b5d8811a7f09) hiding the options; it also updates the documentation for those options to link to the manual (RUST-605).

 RUST-732 Mark the versioned API options public.

---

src/client/executor.rs
src/client/mod.rs
src/test/spec/json/command-monitoring/unified/redacted-commands.json
src/test/spec/json/command-monitoring/unified/redacted-commands.yml
src/test/spec/unified_runner/entity.rs
src/test/spec/unified_runner/mod.rs
src/test/spec/unified_runner/test_file.rs
src/test/spec/unified_runner/test_runner.rs

RUST-873
This pulls in spec test changes, which required adding 1.5 to allowed spec versions and implementing support for `auth` and `observeSensitiveCommands`.  Said tests turned up a bug in the redaction - command response redaction hadn't picked up the `speculativeAuthenticate` clause - which is now fixed.

RUST-873 Test redaction of replies to security-sensitive commands

---

src/test/spec/command_monitoring/operation.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/v2_runner/operation.rs

RUST-580
This PR reimplements the various test runner `TestOperation` traits manually rather than relying on `async_trait`, resulting in much faster compile times of the tests. For context, see https://github.com/rust-lang/rust/issues/87012#issuecomment-881735995.
On my machine, an incremental change to `TestClient::new` (e.g. adding a single `println!`) used to take ~1m15s to run `cargo check --tests`, whereas the same change now takes ~10s. There's still a lot of room for improvement (such a change should ideally be near instant), but this is still a big difference.

RUST-580 Improve compile times of the test suite

---

src/client/executor.rs
src/operation/find/mod.rs
src/test/spec/retryable_reads.rs

RUST-793
This PR boxes the futures returned from `execute_operation` in order to reduce the size of the futures eventually returned to users. 
In Rust, futures are "zero cost" in the sense that they have no hidden heap allocations (i.e. everything is on the stack), and they're implemented as giant enum-like state machines (with the code between each `.await` point as the states) that store all the stack data for each state. Like regular Rust enums, the size of this state machine is equivalent to the size of the largest variant, so the size of our futures are equivalent to the stack space required for the await point that uses the most stack space. Additionally, due to some missing optimizations in the compiler (https://github.com/rust-lang/rust/issues/62958), the size can exponentially …

RUST-793 Reduce size of returned futures

---

src/client/executor.rs
src/client/options/mod.rs
src/cmap/conn/mod.rs
src/cmap/establish/handshake/mod.rs
src/cmap/establish/mod.rs
src/cmap/manager.rs
src/cmap/mod.rs
src/cmap/options.rs
src/cmap/status.rs
src/cmap/test/mod.rs
src/cmap/worker.rs
src/error.rs
src/is_master.rs
src/lib.rs
src/sdam/description/server.rs
src/sdam/description/topology/mod.rs
src/sdam/description/topology/server_selection/mod.rs
src/sdam/description/topology/server_selection/test/mod.rs
src/sdam/description/topology/test/sdam.rs
src/sdam/monitor.rs
src/sdam/state/mod.rs
src/sdam/state/server.rs
src/srv.rs
src/test/mod.rs

RUST-950
This implements the connection establishment portion of load balancer support, i.e.:
- Parsing the `loadBalanced` URI/TXT option
- Modifications to handshake and topology/server type tracking
- Per-`serviceId` connection pool tracking
The work here happened to also encompass RUST-955.

RUST-950 Enable connection to a load balancer

---

src/client/mod.rs
src/client/session/mod.rs
src/client/session/pool.rs
src/sdam/description/server.rs
src/sdam/description/topology/mod.rs
src/test/util/mod.rs

RUST-951
The spec [requires](https://github.com/mongodb/specifications/blob/master/source/load-balancers/load-balancers.rst#driver-sessions) that connections to a load balancer always support sessions, and ignore the `logicalSessionTimeoutMinutes` parameter.  This has to be flagged at `TopologyDescription` creation time because clients to load balancers don't have the monitoring connection that would otherwise update the topology.

RUST-951 Enable sessions on load balancer connections

---

Cargo.toml
src/client/auth/mod.rs
src/client/auth/scram.rs

Includes `hmac = "0.11"` and `pbkdf2 = "0.8"`

RUST-970 Upgrade to hmac 0.11

---

src/client/executor.rs
src/client/options/mod.rs
src/sdam/description/server.rs
src/sdam/description/topology/mod.rs
src/sdam/mod.rs
src/sdam/state/mod.rs

RUST-926
This PR fixes a bug where the driver would always time out trying to determine if sessions were supported when directly connected to a hidden node.

RUST-926 Allow direct connections to hidden nodes

---

src/sdam/description/server.rs

RUST-1002
This change was related to a DRIVERS ticket that we never got a language ticket for. A user [ran into this](https://jira.mongodb.org/browse/RUST-926?focusedCommentId=4011725&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4011725) and since it was a simple change, I figured I'd just go ahead and fix it instead of triaging.

RUST-1002 Allow authentication to all server types except arbiter

---

.evergreen/check-rustdoc.sh
README.md
src/coll/mod.rs
src/db/mod.rs
src/lib.rs

RUST-736
This PR updates the crate's documentation (found in `lib.rs`) to include the 2.0-friendly examples found in the readme. It also adds a table to both the readme and the crate documentation that lists and explains all of the feature flags. Finally, some more guidance was added to the `Collection` documentation about how to use its generic parameter.
To view the new changes locally, you can run `cargo doc --no-deps --open`.

RUST-736 Update driver documentation for 2.0 release

---

README.md
src/lib.rs

RUST-1001
This PR adds a note to the documentation about the dangers of dropping futures returned by the driver before they're completely polled.

RUST-1001 Add warning about not polling futures to completion

---

src/sdam/description/topology/server_selection/test/in_window.rs

RUST-812
This PR increases the iterations of the `in_window::load_balancing_test` and skips it on auth+TLS variants to reduce the amount of flaky failures. The C# driver observed similar flakiness and also took these steps.
Edit: the patch for this PR came back all green :sunglasses:

RUST-827 Improve stability of load-balancing server selection test

---

.evergreen/check-rustdoc.sh
Cargo.toml
src/client/auth/mod.rs
src/lib.rs

In #437, I updated the `check-rustdoc.sh` script to match the one I used in `bson`, but I forgot to change the `-p` flag to say `mongodb`. After fixing that, I saw that the single `rustdoc` invocation wasn't going to work for this crate due to the assumptions we make about only one of tokio and async-std being enabled. This PR then changes the `check-rustdoc.sh` script back to what it was before, and it also fixes a few docs lint issues that were uncovered by doing so.

minor: fix rustdoc lint invocation

---

src/client/session/mod.rs
src/test/spec/unified_runner/entity.rs
src/test/spec/unified_runner/mod.rs
src/test/spec/unified_runner/operation.rs

RUST-1012
This was included for testing, i.e. so that `Entity` could continue to impl `Clone`; however, cloning a session is somewhere between meaningless and actively harmful.  Updated the few places where `Entity` was actually cloned to use one-off projections for the actual subtypes needed.

RUST-1012 remove `Clone` impl from `ClientSession`

---

src/coll/mod.rs

Because `derive` is too conservative, `derive` only implements Clone for `Collection<T>` if T is Clone.
`Collection<T>` does not actually store any value of type T (so T does not need to be Clone).

RUST-993 Implement Clone for Collection<T>

---

src/client/options/mod.rs

Implement `FromStr` for `ServerAddress`.  Allows for calling `"a:1234".parse()` (this requires type annotations or turbofish syntax).

RUST-892 implement FromStr for ServerAddress

---

.evergreen/check-rustdoc.sh
src/lib.rs

The `missing_crate_level_docs` lint was renamed to `rustdoc::missing_crate_level_docs` in rustc 1.55; however, our MSRV doesn't recognize the latter.
Unfortunately, `cfg_attr` doesn't have compiler-provided attributes for compiler version, and the `rustversion` crate that provides macros for such can't be used because macro attributes aren't allowed in inner attribute position, so we're left with suppressing the warning.  I re-enabled it for modules in the crate so the potential surface for problems should be small.

minor: use new rustdoc:: warn prefix

---

src/sdam/monitor.rs

RUST-856
This PR fixes a race between server selection requesting an update to the topology and a monitor subscribing to those requests, which occasionally would result in the `min_heartbeat_frequency` test failing.

RUST-856 Fix race between server selection and server monitoring

---

src/test/cursor.rs
src/test/spec/command_monitoring/mod.rs
src/test/spec/json/command-monitoring/legacy/find.json
src/test/spec/json/command-monitoring/legacy/find.yml
src/test/util/event.rs

RUST-865
Switching find to use SBE (originally scheduled for 5.0, but delayed, see SERVER-59178) will cause a change in `getMore` behavior:  if a batch returned lines up precisely with the `limit`, that will currently exhaust the cursor (i.e. return `id: 0`), but with SBE it will not.  This requires drivers to either call `getMore` an additional time, which will return an empty batch and exhausted cursor, or call `killCursor`.
The Rust driver always loops until cursor exhaustion, so will work correctly post-SBE.  The test added in this PR validates that in this scenario the final `getMore` response is always exhausted.
Some spec tests will fail under the new behavior and have been updated to only run on <= 4.4; the Rust driver skips those tests because they rely on old behavior that the …

RUST-865 Verify correct cursor behavior with SBE

---

src/client/executor.rs
src/client/session/mod.rs
src/cmap/conn/mod.rs
src/operation/abort_transaction/mod.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/v2_runner/mod.rs
src/test/spec/v2_runner/operation.rs

RUST-954
Transaction connection pinning [follows the same rules](https://github.com/mongodb/specifications/blob/master/source/load-balancers/load-balancers.rst#behaviour-with-transactions) as mongos pinning for sharded transactions, so this CL augments that machinery to be able to track a `PinnedConnectionHandle`.
The load balancer spec requires the drivers to track whether a connection is checked out for a cursor vs a transaction vs anything else for the purpose of augmenting the `WaitQueueTimeoutError` message; however, the Rust driver does not support wait queue timeouts, so I've omitted that tracking.

RUST-954 Pin connections for transactions when connected to a load balancer

---

src/client/mod.rs
src/coll/mod.rs

RUST-867
This PR adds some notes to the documentation suggesting some ways to improve performance when using the driver, namely:
- spawn more tasks that use it concurrently
- use a custom data type rather than `Document` as the parameter for `Collection`
- borrow or move in `insert_x` methods rather than cloning

RUST-867 Document some performance best practices

---

src/client/options/mod.rs

RUST-1021 use `ServerAddress::parse` for URI parsing.

RUST-1021 use `ServerAddress::parse` for URI parsing

---

src/client/executor.rs
src/cmap/conn/mod.rs
src/cmap/worker.rs
src/event/cmap.rs
src/event/command.rs
src/is_master.rs

RUST-956
Some events need the `service_id` of the backend behind the load balancer; this adds those.  For the `Command*` events, this would have fit better in the `ConnectionInfo` struct, but unfortunately that's not marked `non_exhaustive` so that would be a breaking change :(
Whichever of this or https://github.com/mongodb/mongo-rust-driver/pull/465 is merged later will need to include the (trivial) event matching code for this field.

RUST-956 Include `service_id` in relevant events

---

src/sdam/description/server.rs
src/sdam/description/topology/mod.rs
src/sdam/state/mod.rs

RUST-952
Some SDAM events are triggered by the heartbeat monitor, which is disabled when connected to a load balancer; this PR synthesizes those events.

RUST-952 Emit SDAM events for load balanced topologies

---

src/coll/mod.rs

RUST-1032 Avoid redundant allocations in `Collection::clone_with_type`

---

src/test/documentation_examples.rs

RUST-781
This removes uses of `unwrap` from example code; only one of these was actually in the example portion.  There are a bunch of remaining `unwrap`s but they're in various places (macros, closures) that would be nontrivial to remove and not produce any benefit.

RUST-781 Remove unwraps from examples

---

Cargo.toml

RUST-1020
This PR updates the `Cargo.toml` to track the master branch of the `bson` repo. This will allow our tests and benchmarks to pull in the latest changes from `bson` since the last release. 
I think in general we should have a policy of always tracking the master of bson right up until the release to ensure we have full coverage. Once we need to do a release, we can switch to the latest `bson` release, and then immediately afterwards we can go back to tracking master.

RUST-1020 Track `bson` master branch

---

src/client/options/mod.rs
src/lib.rs
src/selection_criteria.rs

RUST-1076
This PR removes the macro that conditionally defines all of the drivers modules. Its intent was to make the compile error issued when a user selects more than one async runtime more readable, but it has the side effect of making the docs.rs page for the crate very noisy. After removing the defines, the compile error is still readable, though it does have some extra distracting info.
example:
```
cargo check --no-default-features
Checking mongodb v2.0.0 (/home/patrick/mongo-rust-driver)
error: one of `tokio-runtime`, `async-std-runtime`, or `sync` must be enabled; either enable `default-features`, or enable one of those features specifically in your Cargo.toml
--> src/lib.rs:376:1
|
376 | / compile_error!(
377 | |     "one of `tokio-runtime`, `async-std-runtime`, or `sync` must …
```

RUST-1076 Remove conditional module definition

---

src/client/options/mod.rs
src/client/options/test.rs

RUST-1060 Omit non-pub fields from debug output of `ClientOptions`

---

src/client/options/mod.rs
src/client/options/test.rs

Backport of RUST-1060 to 2.0.2.

RUST-1060 Omit non-pub fields from debug output of ClientOptions (2.0.x)

---

src/client/executor.rs
src/client/mod.rs
src/client/options/mod.rs
src/client/session/mod.rs
src/client/session/test.rs
src/client/session/test/causal_consistency.rs
src/client/session/test/mod.rs
src/cmap/conn/command.rs
src/coll/options.rs
src/concern/mod.rs
src/operation/aggregate/mod.rs
src/operation/aggregate/test.rs
src/operation/count/mod.rs
src/operation/count/test.rs
src/operation/count_documents/mod.rs
src/operation/count_documents/test.rs
src/operation/distinct/mod.rs
src/operation/find/mod.rs
src/operation/find/test.rs
src/operation/mod.rs
src/operation/run_command/mod.rs
src/test/client.rs
src/test/util/mod.rs

This PR provides support for [causal consistency](https://github.com/mongodb/specifications/blob/master/source/causal-consistency/causal-consistency.rst).
The change that is needed to support causally consistent sessions is that `readConcern.afterClusterTime` now needs to be included in all commands that are part of a causally consistent session that take a `readConcern`.  `readConcern.afterClusterTime` must be set to the `operationTime` field of the `ClientSession` struct (initialized to `None`).  The `operationTime` field of the `ClientSession` struct must get updated to the `operationTime` field of the server's response to any command that is part of a causally consistent session (this field is included on success or error).
The main difficulty is that `readConcern.level` now is not …

RUST-48 Causal consistency support

---

src/change_stream/event.rs
src/change_stream/mod.rs
src/change_stream/options.rs
src/change_stream/session.rs
src/client/mod.rs
src/coll/mod.rs
src/db/mod.rs
src/lib.rs
src/options.rs
src/test/documentation_examples/mod.rs

RUST-519
This is largely a directly transliteration of the [spec](https://github.com/mongodb/specifications/blob/master/source/change-streams/change-streams.rst), and is heavily based on [the PR](https://github.com/mongodb/mongo-rust-driver/commit/2f16ab6600457cbf6d24a90603301b3554f5d71f) implementing this in the change-streams branch.  Notable changes from that PR:
* `ChangeStreamEvent` is generic over the document type.
* `ChangeStream` is generic over the item type.
* `watch` assumes a `ChangeStreamEvent<_>` as the returned stream item type, and notes in documentation that if the structure is changed it'll need a `with_type` call.

RUST-519 Implement (but do not expose) the public change streams API

---

src/client/mod.rs
src/cmap/establish/test.rs
src/sdam/description/topology/server_selection/mod.rs

RUST-844
This PR fixes an issue which I think occurs when the test attempts to authenticate against a node that the credentials haven't replicated to yet. The fix is to just always run the test against the primary on replica sets.

RUST-844 Fix flaky speculative authentication test

---

src/client/mod.rs
src/client/session/test/mod.rs
src/cmap/worker.rs
src/lib.rs
src/sdam/description/server.rs
src/sdam/description/topology/server_selection/mod.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/sdam/description/topology/server_selection/test/logic.rs
src/sdam/description/topology/server_selection/test/mod.rs

RUST-1100
This PR fixes a test that was occasionally failing due to a race between replication and the test. It also fixes a bug in server selection wherein unavailable servers and arbiters could be selected via predicate-based selection criteria (RUST-1113). Additionally, this PR exports the types defined in `sdam::public` (RUST-1114).

RUST-1100 Fix `find_and_getmore_share_session` test

---

.evergreen/releases.yml

This PR fixes the release publishing config, which is currently broken because the `install-node.sh` script can't find the `$PROJECT_DIRECTORY` variable.

minor: fix publish release evergreen config

---

src/bson_util/mod.rs
src/operation/insert/mod.rs
src/operation/insert/test.rs

RUST-1133
We implemented some of the raw BSON functionality in the driver itself as a temporary measure until the BSON library had its own support for it. Now that it does, we can remove these driver-only implementations and update to use the BSON library's versions instead.

RUST-1133 Update driver to use the raw BSON API

---

README.md

The latest version always needs to be reflected in the README because, for better or worse, the [MongoDB Rust Driver official documentation section "Installation"](https://docs.mongodb.com/drivers/rust/#installation), delegates to this repo's "master" branch README for user installation instructions and we of course don't want to be encouraging users to use old versions of the driver by default.

Updated readme reference to driver version to 2.1.0

---

.evergreen/run-driver-benchmarks.sh
benchmarks/Cargo.toml
benchmarks/src/bench/find_many.rs
benchmarks/src/bench/find_one.rs
benchmarks/src/bench/json_multi_export.rs
benchmarks/src/bench/json_multi_import.rs
benchmarks/src/main.rs
benchmarks/src/models.rs

RUST-1103
This PR introduces two new benchmarks: find many (raw BSON) and find many (serde struct). It also updates the multi export benchmark to use raw BSON, resulting in a speedup.
I didn't include any new versions of the find one by id benchmark, since using raw BSON didn't actually change anything there. I believe this is due to the test being bottlenecked by network I/O rather than BSON serialization. 
I also didn't include any borrowed deserialization benchmarks for any case, since it also didn't make any noticeable difference. I think we'd need to use a data set that has documents much larger than the tweet one provided with the microbenchmarks.
Lastly, I didn't update the multi-import benchmark to use raw documents, since it currently doesn't result in a speedup due to RUST-1132. …

RUST-1103 Update microbenchmarks to use raw BSON

---

src/db/options.rs

Our `TimeseriesOptions` struct does not derive `TypedBuilder`, so users currently do not have a way to construct these options (see #556). Thank you to @fuwaneko for pointing out this issue!

minor: derive `TypedBuilder` for `TimeseriesOptions`

---

src/lib.rs

Fixes the links to external crates on our [docs.rs page](https://docs.rs/mongodb/latest/mongodb/) that are currently broken.

minor: fix external crate links

---

src/change_stream/event.rs
src/change_stream/mod.rs
src/client/executor.rs
src/cmap/test/integration.rs
src/coll/mod.rs
src/error.rs
src/sdam/description/topology/test/sdam.rs
src/sdam/test.rs
src/test/change_stream.rs
src/test/mod.rs
src/test/spec/retryable_reads.rs
src/test/util/mod.rs

RUST-1149
This implements the prose tests for change streams, with the exception of test 6, which is (a) tricky to observe and (b) essentially guaranteed to be correct by the design of the Rust driver.  Some relatively minor updates were required to the change stream implementation as a result of bugs found by these tests.

RUST-1149 Prose tests for change streams.

---

src/change_stream/mod.rs
src/change_stream/session.rs
src/sync/change_stream.rs
src/sync/client/mod.rs
src/sync/coll.rs
src/sync/db.rs
src/sync/mod.rs

RUST-1104
This adds the sync wrappers for the `[Session]ChangeStream` types and the `watch[_with_session]` methods.

RUST-1104 sync wrapper for the change stream API

---

src/bson_util/mod.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/test/util/event.rs
src/test/util/mod.rs

RUST-812
This PR makes the following changes to hopefully eliminate the remaining flakiness in the `in_window::load_balancing_test`, which verifies that the operation-count tracking server selection algorithm successfully routes requests away from busy servers:
- Add a 30 second local threshold config to the client, ensuring both mongoses are always in the latency window
- Use SDAM monitoring events to ensure both mongoses are discovered before starting the test
From testing, it seems that this (in conjunction with skipping on auth + tls) eliminates the random failures, but we'll have to wait and see if they crop up again. Should these changes prove successful, I'll update the spec to require them so other drivers can avoid similar errors (DRIVERS-1926)

RUST-812 Reduce flakiness of `in_window::load_balancing_test`

---

src/change_stream/event.rs
src/change_stream/mod.rs
src/change_stream/session.rs
src/client/mod.rs
src/coll/mod.rs
src/db/mod.rs
src/lib.rs
src/options.rs
src/sync/change_stream.rs
src/sync/client/mod.rs
src/sync/coll.rs
src/sync/db.rs
src/sync/mod.rs

RUST-1106
This PR marks the modules and `watch` functions `pub`, removes the `ignore` clause on the rustdoc examples (and fixes those examples), and cleans up a bunch of unused imports that apparently weren't being checked while it was `pub(crate)`.

RUST-1106 Make the change streams API visible

---

.evergreen/config.yml

RUST-1154
This doesn't fix the actual issue, but it does mean that the failures are flagged as system failures rather than test failures.

RUST-1154 Fail evergreen tasks if precommands fail

---

.evergreen/config.yml
src/bson_util/mod.rs
src/client/options/mod.rs
src/cmap/conn/wire/test.rs
src/cmap/establish/handshake/mod.rs
src/cmap/options.rs
src/test/mod.rs
src/test/spec/connection_stepdown.rs
src/test/spec/unified_runner/test_runner.rs
src/test/util/mod.rs

RUST-1163
This PR updates the load balancer testing harness to accommodate the recent changes that broke it.

RUST-1163 Fix load balancer tests

---

src/test/spec/json/change-streams/unified/change-streams-errors.json
src/test/spec/json/change-streams/unified/change-streams-errors.yml
src/test/spec/json/change-streams/unified/change-streams-resume-allowlist.json
src/test/spec/json/change-streams/unified/change-streams-resume-allowlist.yml
src/test/spec/json/change-streams/unified/change-streams-resume-errorLabels.json
src/test/spec/json/change-streams/unified/change-streams-resume-errorLabels.yml
src/test/spec/json/change-streams/unified/change-streams.json
src/test/spec/json/change-streams/unified/change-streams.yml
src/test/spec/unified_runner/mod.rs

The tests need to set `useMultipleMongoses: false` for both clients to avoid being vulnerable to race conditions and topological flakiness.
Also updated the test runner to output the description of the test when an expected error isn't found.

minor: fix change stream tests

---

src/test/client.rs

RUST-1163 (kinda)
In DRIVERS-1983, the auth configs in drivers-evergreen-tools were fixed to actually enable auth, exposing a few LB failures in our runner. This PR fixes those tests by ensuring the `loadBalanced=true` option is always respected.

RUST-1163 Fix load balancer auth tests

---

Cargo.toml
README.md
src/lib.rs

RUST-1138 Add `bson-serde_with` feature flag

---

src/client/options/mod.rs
src/test/documentation_examples/mod.rs

Grepped for "versioned" in the driver and replaced all references with "stable". The only terminology I didn't change was in the spec tests as the directory in the specifications repo hasn't been renamed.

RUST-1173 Replace "Versioned API" references with "Stable API"

---

src/test/documentation_examples/mod.rs

Someone on the docs team reached out to let me know that they're still relying upon the stable API examples to be delineated with "Start Versioned API Example...", so this PR reverts the changes made to those comments in #585.

minor: revert changes to documentation example comments

---

.evergreen/check-clippy.sh
.evergreen/install-dependencies.sh
src/change_stream/event.rs
src/operation/aggregate/change_stream.rs
src/test/spec/unified_runner/matcher.rs

This PR fixes our existing clippy errors and pins clippy to the latest version (1.59.0).

RUST-1124 Pin version of clippy used in CI

---

src/bson_util/mod.rs
src/client/auth/scram.rs
src/client/auth/test.rs
src/client/options/mod.rs
src/operation/aggregate/test.rs
src/operation/count/test.rs
src/operation/count_documents/test.rs
src/operation/create/test.rs
src/operation/create_indexes/test.rs
src/operation/delete/test.rs
src/operation/distinct/test.rs
src/operation/drop_collection/test.rs
src/operation/drop_database/test.rs
src/operation/drop_indexes/test.rs
src/operation/find/test.rs
src/operation/find_and_modify/test.rs
src/operation/get_more/test.rs
src/operation/insert/test.rs
src/operation/list_collections/test.rs
src/operation/list_databases/test.rs
src/operation/list_indexes/test.rs
src/operation/run_command/test.rs
src/operation/test.rs
src/operation/update/test.rs
src/test/spec/unified_runner/matcher.rs
src/test/spec/unified_runner/test_file.rs

Updates any tests without async code to use `#[test]`.

RUST-1102 Run sync tests with `#[test]` attribute

---

.evergreen/install-dependencies.sh

RUST-1154
The problem is indeed some sort of cache corruption; the install logs of the fetches that fail are always from cache.  I'm not entirely sure how this happens because as far as I can tell the default cache dir is distinct for a given evergreen run, so there shouldn't be any concurrent access to corrupt it 🤷 .  The fix is to force each installation to use a fresh, unique directory as the cache directory.
I left the debugging code to dump the logfile present because otherwise it's pretty hard to figure out what's going wrong if the install fails, and the logfiles are not easily retrievable post facto.

RUST-1154 Fix junit-report-merger install failures

---

.evergreen/run-async-std-tests.sh
.evergreen/run-serverless-tests.sh
.evergreen/run-tokio-tests.sh

RUST-1210
Because bash treats ``false || true`` to be a success by default, test scripts with ``cargo test ... | tee ...`` would mask any test or compile failures.  Setting `pipefail` fixes that, but in turn meant that test failures would immediately exit the script because of ``errexit``, preventing the generated reports from being converted and merged.  This PR fixes *that* by unsetting ``errexit`` for that portion of the script and keeping a "running or" of the ``cargo test`` exit statuses.

RUST-1210 Expose test failures and compile failures

---

src/test/documentation_examples/mod.rs

Skips a documentation test that now fails on latest due to count being added to the stable API.

minor: skip failing documentation test

---

src/cmap/conn/command.rs
src/operation/insert/mod.rs
src/operation/update/mod.rs
src/test/coll.rs

These changes work around a somewhat commonly encountered issue in the server where long error messages containing multi-byte characters are truncated incorrectly such that they are no longer valid UTF-8.
From digging through all of the related tickets for the server and drivers, this only ever seems to be observed in duplicate key errors, which I believe can only result from `insert` and `update` commands, so I've limited this PR to those two operations. It seems possible it could come up elsewhere, but I figured we could start with this and expand our usage of the lossy decoding later if the need arises.
Before my changes, all of the errors below, which are now duplicate key errors, would instead be something like
```
Error { kind: InvalidResponse { message: "invalid utf-8 sequence of 1 …
```

RUST-886 Use lossy UTF-8 decoding for responses to insert and update commands

---

src/test/cursor.rs

This always fails on serverless now, so skipping it there.

RUST-1217 Skip tailable cursor test on serverless

---

src/cmap/establish/handshake/mod.rs
src/error.rs
src/sdam/description/topology/test/sdam.rs
src/test/spec/connection_stepdown.rs

RUST-805
Most of the oppressive language was removed in #380, but a few were missed, which this PR fixes.

RUST-805 Remove remaining oppressive language from the source code

---

Cargo.toml
src/cmap/establish/handshake/mod.rs

RUST-1268
Switches the driver to use `rustc_version_runtime` to retrieve the rustc version used for compilation for inclusion in the driver handshake metadata.
Previously, on a machine where rustc was available the platforms field looked like this:
```
"rustc 1.60.0 stable (2022-04-04) with tokio" // stable release
"rustc 1.62.0 nightly (2022-04-11) with tokio" // nightly release
```
When rustc is not available, this field was null.
Now, it looks like this (slightly different due to the formatting of `VersionMeta.short_version_string`, but the relevant info is still there and in a similar format):
```
"rustc 1.60.0 (7737e0b5c 2022-04-04) with tokio" // stable release
"rustc 1.62.0-nightly (90ca44752 2022-04-11) with tokio" // nightly release
```
It doesn't seem like we test this at all …

RUST-1268 Correctly report rustc version used for compilation in handshake

---

src/change_stream/event.rs
src/test/spec/change_streams.rs
src/test/spec/json/change-streams/unified/change-streams.json
src/test/spec/json/change-streams/unified/change-streams.yml
src/test/spec/unified_runner/entity.rs
src/test/spec/unified_runner/matcher.rs
src/test/spec/unified_runner/mod.rs
src/test/spec/unified_runner/operation.rs

RUST-1168
This PR syncs tests that check handling of new operation types and new fields in various places.  New operation types required setting up some serde helper types, and passing a test that needed a field preserved required switching from `ChangeStream<ChangeStreamEvent<Document>>` to `ChangeStream<Document>` in test contexts.

RUST-1168 Future compatibility for change streams

---

src/sdam/description/topology/test/sdam.rs
src/test/util/mod.rs

RUST-1017
This PR attempts to reduce the flakiness of the `heartbeat_events` test by scoping the failpoint only to commands issued with a given appname to prevent collisions with other tests. I *think* this is the cause of the occasional failures, but we'll have to see.

RUST-1017 Reduce flakiness of SDAM `heartbeat_events` test

---

Cargo.toml

Bump to a newer version of rustc_version_runtime which does not need to write to the `src` directory of the crate. docs.rs builds the docs on a read-only file system which does not permit that.

RUST-1272 Bump rustc_version_runtime to fix docs.rs build

---

src/change_stream/event.rs
src/change_stream/options.rs
src/db/options.rs
src/test/change_stream.rs
src/test/spec/json/change-streams/unified/change-streams-pre_and_post_images.json
src/test/spec/json/change-streams/unified/change-streams-pre_and_post_images.yml

RUST-1166
This adds the options and output fields to allow pre-images to be reported by change streams.

RUST-1166 Add support for pre-images in change streams.

---

src/cmap/conn/mod.rs
src/cmap/conn/stream_description.rs
src/cmap/conn/wire/message.rs
src/hello.rs
src/sdam/description/topology/test/sdam.rs

RUST-616
This adds support for the `maxMessageSizeBytes` hello response field, and validates message header `length` against that maximum.

RUST-616 Error if message is too long

---

src/client/options/mod.rs
src/cmap/test/file.rs
src/sdam/description/topology/mod.rs
src/sdam/description/topology/server_selection/mod.rs
src/sdam/description/topology/server_selection/test/logic.rs
src/sdam/mod.rs
src/sdam/monitor.rs
src/selection_criteria.rs

RUST-1080
This PR updates the client options validator to error on invalid maxStalenessSeconds values, accept -1 to mean "no max staleness", and updates the maxStaleness spec test runner to cover error cases. This PR also completes RUST-1079 by ensuring all CMAP spec test fields are deserialized.

RUST-1080 Improve maxStalenessSeconds parsing

---

src/sdam/description/topology/server_selection/test/in_window.rs
src/test/util/event.rs

RUST-1035
This PR makes some updates to the load balancing server selection prose test to make it hopefully less flaky.
Relevant test here: https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection-tests.rst#prose-test

RUST-1035 Fix flaky server selection test

---

src/test/spec/json/crud/unified/estimatedDocumentCount-comment.json
src/test/spec/json/crud/unified/estimatedDocumentCount-comment.yml
src/test/spec/json/crud/unified/estimatedDocumentCount.json
src/test/spec/json/crud/unified/estimatedDocumentCount.yml
src/test/spec/json/versioned-api/README.rst
src/test/spec/json/versioned-api/crud-api-version-1-strict.json
src/test/spec/json/versioned-api/crud-api-version-1-strict.yml
src/test/spec/json/versioned-api/crud-api-version-1.json
src/test/spec/json/versioned-api/crud-api-version-1.yml

RUST-1216
This PR syncs the `estimated_document_count` tests to use the correct runOnRequirements (the backport of adding `count` to the stable API missed the cut for 5.0.8).
This PR also syncs in a new test that was added to ensure `estimated_document_count` works against views.

RUST-1216 Use correct runOnRequirements in estimatedDocumentCount tests

---

src/sdam/test.rs
src/sdam/topology.rs

RUST-332 / RUST-358
This causes servers that don't match the repl set name given in the connection string to be marked as unknown, so any operation will return an error.

RUST-332 Return an error for replica set name mismatch

---

src/change_stream/mod.rs
src/test/change_stream.rs

RUST-1191
This PR updates the driver's implementation of prose test 13 from the change stream spec, which is the following:
>For a ChangeStream under these conditions:
>
>    The batch is not empty.
>    The batch has been iterated up to but not including the last element.
>
>Expected result:
>
>    getResumeToken must return the _id of the previous document returned.
Our implementation of the test used two separate `insert_one` operations to generate the events. I think this caused sporadic failures on sharded clusters due to the events not arriving in the same batch sometimes. Change Streams are much faster on replica sets, so this problem wasn't as common there.
The test has been updated to use a single `insert_many` operation instead, along with a majority write concern, which seems …

RUST-1191 Reduce flakiness of `change_stream::batch_mid_resume_token` test

---

src/client/executor.rs
src/event/sdam/mod.rs
src/operation/mod.rs
src/sdam/description/server.rs
src/sdam/monitor.rs
src/test/client.rs
src/test/util/event.rs
src/test/util/mod.rs

RUST-1274
This backports the fix for `InvalidOptions` errors that are seen when `commitTransaction` commands are retried due to connection check out failures. The fix for this was included on `main` in #628.

RUST-1274 Fix commitTransaction on check out retries

---

.evergreen/check-all.sh
.evergreen/check-clippy.sh
.evergreen/check-rustdoc.sh
.evergreen/check-rustfmt.sh
.evergreen/compile-only-async-std.sh
.evergreen/compile-only-tokio.sh
.evergreen/compile-only.sh
.evergreen/config.yml
.evergreen/configure-rust.sh
.evergreen/env.sh
.evergreen/feature-combinations.sh
.evergreen/install-dependencies.sh
.evergreen/release-danger-do-not-run-manually.sh
.evergreen/run-async-std-atlas-tests.sh
.evergreen/run-atlas-tests.sh
.evergreen/run-aws-tests.sh
.evergreen/run-bson-benchmarks.sh
.evergreen/run-compile-benchmarks.sh
.evergreen/run-connection-string-tests.sh
.evergreen/run-driver-benchmarks.sh
.evergreen/run-ocsp-test.sh
.evergreen/run-plain-tests.sh
.evergreen/run-tokio-atlas-tests.sh
manual/test.sh

Attempts to better simulate the docs.rs build environment in our check-rustdoc test by making the cargo registry directory read-only.
Since the `chmod` makes the cargo registry unusable for future tasks that need to e.g. download different dependencies than the docs one, this also required changing how we install rustup cargo so that it happens in the project directory and is cleaned up at the end of each task, which is the "right" thing to do on Evergreen anyway rather than writing to the shared home directory.
Here's a[ patch](https://spruce.mongodb.com/task/mongo_rust_driver_lint_check_rustdoc_patch_279322cae0fe4f2302ed14fd541de640eebd75c4_627af92132f4173983980fd9_22_05_10_23_45_53/logs?execution=0) showing that check-rustdoc now fails if using the old version of …

RUST-1283 Build docs in read-only directory and install cargo in project directory on Evergreen

---

src/db/options.rs
src/index/options.rs
src/test/spec/json/collection-management/README.rst
src/test/spec/json/collection-management/clustered-indexes.json
src/test/spec/json/collection-management/clustered-indexes.yml

RUST-1271
This adds the fields needed to support clustered indexes, and syncs the new tests for such.

RUST-1271 Support clustered indexes for all collections

---

src/test/spec/json/change-streams/unified/change-streams-errors.json
src/test/spec/json/change-streams/unified/change-streams-errors.yml
src/test/spec/json/change-streams/unified/change-streams-pre_and_post_images.json
src/test/spec/json/change-streams/unified/change-streams-pre_and_post_images.yml
src/test/spec/json/change-streams/unified/change-streams-resume-allowlist.json
src/test/spec/json/change-streams/unified/change-streams-resume-allowlist.yml
src/test/spec/json/change-streams/unified/change-streams-resume-errorLabels.json
src/test/spec/json/change-streams/unified/change-streams-resume-errorLabels.yml
src/test/spec/json/change-streams/unified/change-streams.json
src/test/spec/json/change-streams/unified/change-streams.yml

RUST-1327
Change stream tests on sharded clusters occasionally fail with unexpected `delete` / `invalidate` events ([example](https://evergreen.mongodb.com/lobster/evergreen/test/mongo_rust_driver_tests__async_runtime~tokio_auth_and_tls~auth_and_tls_compressor~zstd_compression_os~ubuntu_18.04_test_4.4_sharded_cluster_patch_0be1d677dc86a0981964f530d4b7d7e727e0b678_6287abc356234305617b1532_22_05_20_14_55_02/0/4e37ff7dfa11f725f536cdfeacd4bbe5/#bookmarks=0%2C123&l=1&shareLine=1)); these failures need investigation but in the meanwhile the tests are being restricted to replsets to reduce noise.
This sync also picked up the changes for RUST-1286.

RUST-1327 Restrict change stream tests to replsets

---

src/client/options/mod.rs
src/client/options/test.rs

RUST-1193
This renames and makes public the existing `ClientOptionsParser` struct as `ConnectionString` to allow for parsing and modeling connection strings without requiring IO for DNS lookup.  I was deliberately conservative in this addition - there's no builder type, so the only way to construct one is from a string, and only those fields that were already directly exposed in `ClientOptions` are also exposed here.

RUST-1193 Provide a public `ConnectionString` type

---

.evergreen/config.yml
.evergreen/run-serverless-tests.sh
Cargo.toml
src/client/options/mod.rs
src/client/session/test/mod.rs
src/cmap/establish/test.rs
src/cmap/test/integration.rs
src/cmap/test/mod.rs
src/compression/test.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/sdam/description/topology/test/sdam.rs
src/sdam/srv_polling/test.rs
src/sdam/test.rs
src/sync/test.rs
src/test/change_stream.rs
src/test/client.rs
src/test/coll.rs
src/test/mod.rs
src/test/spec/command_monitoring/mod.rs
src/test/spec/connection_stepdown.rs
src/test/spec/initial_dns_seedlist_discovery.rs
src/test/spec/ocsp.rs
src/test/spec/retryable_reads.rs
src/test/spec/retryable_writes/mod.rs
src/test/spec/unified_runner/test_runner.rs
src/test/spec/versioned_api.rs
src/test/util/mod.rs

RUST-1090
The original task here was to fix the serverless testing tasks, which had started failing recently after some changes were made to the drivers-evergreen-tools scripts for setting up serverless testing. See DRIVERS-1967 for details, but essentially the required changes for that were:
* update the `SERVERLESS_DRIVERS_GROUP` variable on our Evergreen project
* drivers-evergreen-tools only generates a single URI now, `SERVERLESS_URI`; always use this for serverless tests
* When testing against serverless, ignore `useMultipleMongoses` and always use the `SERVERLESS_URI` / `SINGLE_MONGOS_LB_URI`
* run _all_ unified spec tests against serverless
This was quite straightforward in Swift (see https://github.com/mongodb/mongo-swift-driver/pull/754), but presented some extra challenges in …

RUST-1090 Fix serverless tests

---

.evergreen/config.yml

* Add 6.0 tasks
* Add "rapid" tasks (these test against the latest "rapid" release, so currently 5.3)
* Add load balancer testing for all server versions 5.0+ now that LB support was backported (this was a quick win we had a ticket for already, RUST-1316)

RUST-1299, RUST-1316: Update server versions tested on Evergreen

---

src/cmap/conn/mod.rs
src/cmap/establish/handshake/mod.rs
src/event/command.rs
src/hello.rs
src/sdam/description/topology/test/sdam.rs
src/test/spec/json/command-monitoring/unified/pre-42-server-connection-id.json
src/test/spec/json/command-monitoring/unified/pre-42-server-connection-id.yml
src/test/spec/json/command-monitoring/unified/server-connection-id.json
src/test/spec/json/command-monitoring/unified/server-connection-id.yml
src/test/spec/unified_runner/matcher.rs
src/test/spec/unified_runner/mod.rs
src/test/spec/unified_runner/test_event.rs
src/test/spec/unified_runner/test_runner.rs

RUST-910
We'll want to expose this in command log messages, so I went ahead with adding this to the monitoring events.

RUST-910 Expose server connectionId in command monitoring events

---

src/change_stream/mod.rs
src/cursor/common.rs
src/cursor/mod.rs
src/test/change_stream.rs

RUST-1191
This PR makes another attempt at reducing the flakiness of the `change_stream::mid_batch_resume_token` test.

RUST-1191 Ensure change stream is in proper state in mid_batch_resume_token test

---

.evergreen/benchmarks.yml
.evergreen/config.yml
.evergreen/install-dependencies.sh
.evergreen/releases.yml
.gitignore

This modularizes our script for installing dependencies to accept a list of one or more components to install. 
Probably most notably this saves us from installing everything related to producing junit reports in cases where we do not actually produce a junit test report.
Here's a [patch](https://spruce.mongodb.com/version/62cc87faa4cf47435a7535ac/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC); the failures are all either due to the new change stream test issue on latest or the new mongo-orchestration issue on latest; see threads in driver-devs for more details.

RUST-1348 modularize Evergreen dependency installation script

---

src/test/spec/change_streams.rs

This test is going to need to be changed or removed (see DRIVERS-2387); skipping it against server >= 6.1 in the meantime.

Skip change streams test failing against server latest

---

.evergreen/releases.yml

Latest release task failed due to PROJECT_DIRECTORY being unset, which causes the configure-rust.sh script to think `/.cargo` is CARGO_HOME rather than `$PROJECT_DIRECTORY/.cargo`. 
Can't guarantee this fixes the automation, but one step closer to fixed anyway...

[2.3.x] Release automation fix

---

src/client/csfle.rs
src/client/mod.rs
src/coll/mod.rs
src/coll/options.rs
src/db/mod.rs
src/db/options.rs
src/operation/drop_collection/test.rs

RUST-1383
Per the [spec](https://github.com/mongodb/specifications/blob/master/source/client-side-encryption/client-side-encryption.rst#queryable-encryption-create-and-drop-collection-helpers), `create` and `drop` need additional operations when acting on collections with encrypted fields.  The actual operations here are pretty straightforward; following the right defaulting logic for the associated `encrypted_fields` map is the majority of the complexity here.

RUST-1383 Create or drop auxiliary collections when doing so for a collection with encrypted fields.

---

deny.toml

RUST-1413
This also removes a now-obsolete advisory from the ignore list.  [Successful evergreen run](https://evergreen.mongodb.com/lobster/evergreen/task/mongo_rust_driver_lint_check_cargo_deny_patch_1d52ed798ebb11c6a4e5ab5b67fe5b974dd89f97_62ec10235623434ce224d36a_22_08_04_18_30_01/0/task#bookmarks=0%2C984&l=1&shareLine=885).

RUST-1413 Add Unicode-DFS-2016 to the list of allowed licenses

---

Cargo.toml
src/db/mod.rs
src/gridfs.rs
src/gridfs/options.rs
src/lib.rs

WIP: Adding GridFS support to the Rust Driver.

RUST-1392 Add GridFS support: Implement public API with placeholder code

---

src/test/spec/collection_management.rs
src/test/spec/json/collection-management/createCollection-pre_and_post_images.json
src/test/spec/json/collection-management/createCollection-pre_and_post_images.yml
src/test/spec/json/collection-management/modifyCollection-pre_and_post_images.json
src/test/spec/json/collection-management/modifyCollection-pre_and_post_images.yml

RUST-1295
This is mostly just a test sync; however, one of the test files is exercising the `modifyCollection` helper, which the Rust driver doesn't have, so it needed a code change to skip that.  I couldn't find a bug to implement that, so I left it with a non-TODO comment.

RUST-1295 Sync tests for pre and post image options in collection helpers

---

Cargo.toml

Hello there! I noticed that one of my projects had multiple duplicate dependencies due to `mongodb`. This PR bumps up the crate versions. Most of the bumps were patch-level. The notable bumps are noted below:
Crate | Old | New | Notes
----- | --- | --- | -----
`rustls-pemfile` | `0.3` | `1.0` | The [changelog](https://github.com/rustls/pemfile#release-history) declares no API changes. This is a safe major version bump.
`pbkdf2` | `0.10` | `0.11` | [Now uses the `2021` edition with MSRV `1.57`.](https://github.com/RustCrypto/password-hashes/blob/master/pbkdf2/CHANGELOG.md#0110-2022-03-28)
Sadly, the `time` crate appears to be an unremovable duplicate crate (for now) since `chrono` requires the `time` crate at version `0.1` while `bson` requires it at version `0.3`. The current maintainers …

Deps: bump various dependencies

---

src/client/csfle.rs
src/client/csfle/client_encryption.rs
src/client/csfle/state_machine.rs
src/client/executor.rs
src/concern/mod.rs
src/gridfs.rs
src/lib.rs

RUST-1385
This implements the `ClientEncryption` struct which provides the explicit encryption API.  This required a bit of refactoring to allow a `Ctx` to be executed independently of a `Client`, but is otherwise mostly just data plumbing; the API is just a wrapper around CRUD operations plus `Ctx` operations.

RUST-1385 Implement explicit encryption

---

src/test/spec/crud_v1/mod.rs

RUST-412
I checked and the v2 runner, retryable writes runner, and unified runner all do this already.

RUST-412 Use sort when verifying the outcome of CRUD v1 tests

---

Cargo.toml

RUST-1450
This release no longer depends on the now unmaintained ansi_term crate.

RUST-1450 Bump pretty_assertions dependency to 1.3.0

---

Cargo.toml
src/client/csfle.rs
src/client/csfle/client_encryption.rs
src/client/csfle/state_machine.rs
src/operation/raw_output.rs
src/operation/run_command/mod.rs
src/runtime/mod.rs
src/runtime/process.rs

RUST-1396
[Spec](https://github.com/mongodb/specifications/blob/master/source/client-side-encryption/client-side-encryption.rst#spawning-mongocryptd); this is the "If spawning is necessary..." clause.  Control of mongocryptd spawning moved into the `CryptExecutor`, which IMO mostly made things a bit cleaner.  The split between `CryptExecutor::new_implicit` and `::new_explicit` is a bit clunky, but because one needs async and the other doesn't it seemed necessary.  Sadly, we're probably a ways off from dependently typed function keywords :)

RUST-1396 Respawn mongocryptd on server selection failure

---

.evergreen/config.yml

RUST-1456
This PR updates our evergreen config to create an empty file in the "run aws auth test with aws EC2 credentials" test so as to avoid ingesting environment variables from prior tests in the task.

RUST-1456 Ensure credentials from prior test runs are not used in EC2 AWS auth test

---

src/runtime/worker_handle.rs
src/sdam/description/topology/mod.rs
src/sdam/monitor.rs
src/sdam/test.rs
src/sdam/topology.rs
src/test/util/event.rs

RUST-1443
This PR fixes a bug where server monitors would continue executing even after a server had been removed from the topology.

RUST-1443 Stop executing server monitors after the server has been closed (2.3 backport)

---

manual/src/reading.md
src/change_stream/mod.rs
src/change_stream/session.rs
src/cursor/mod.rs
src/cursor/session.rs

This PR documents the fact that change streams and cursors are closed automatically via their drop implementations.
Addresses the question filed in #741.

minor: document cursor/change stream `Drop` implementations

---

src/client/options/mod.rs
src/client/options/test.rs
src/sdam/monitor.rs
src/sdam/test.rs
src/sdam/topology.rs

RUST-1443
This PR forward-ports the test added in #733 that verifies that monitors stop executing after their servers are removed from the topology. Running the test yielded a panic in the monitoring task due to a subtraction overflow (heartbeatFrequencyMS < minHeartbeatFrequencyMS), which made me notice we weren't validating heartbeatFrequencyMS when constructing a client via `ClientOptions` directly. I also fixed that here (RUST-1476).

RUST-1443 Ensure monitors close after server is removed from topology

---

src/runtime/stream.rs

RUST-1464
This PR backports a fix made in #721 that updated our async-std connection establishment to be `async` instead of blocking. This ensures that we don't halt the progress of other async tasks managed by the `async-std` runtime.

RUST-1464 Use async connection establishment when using async-std (2.3.x backport)

---

deny.toml

Backport from 342c35f646a96d905fd67c253f08422aa946dd7a.

RUST-1413 Add Unicode-DFS-2016 to the list of allowed licenses (#718)

---

.evergreen/releases.yml

I'm not sure how to test this short of pushing another release, but this _should_ fix the problem we had with 2.3.1.

minor: remove expansion.yml after load

---

.evergreen/MSRV-Cargo.lock
Cargo.toml
src/client/csfle/state_machine.rs

RUST-1490
This switches to using the `num_cpus` crate instead of the stdlib function that's not available in our MSRV; it also updates the lock file to use a more recent git revision of `bson`, which had some knock-on changes.

RUST-1490 Fix build errors with csfle enabled

---

Cargo.toml
src/client/csfle/state_machine.rs
src/db/mod.rs
src/error.rs
src/gridfs.rs
src/gridfs/download.rs
src/gridfs/options.rs
src/test/spec/gridfs.rs
src/test/spec/json/gridfs/README.rst
src/test/spec/json/gridfs/delete.json
src/test/spec/json/gridfs/delete.yml
src/test/spec/json/gridfs/download.json
src/test/spec/json/gridfs/download.yml
src/test/spec/json/gridfs/downloadByName.json
src/test/spec/json/gridfs/downloadByName.yml
src/test/spec/json/gridfs/upload-disableMD5.json
src/test/spec/json/gridfs/upload-disableMD5.yml
src/test/spec/json/gridfs/upload.json
src/test/spec/json/gridfs/upload.yml
src/test/spec/mod.rs
src/test/spec/unified_runner/entity.rs
src/test/spec/unified_runner/matcher.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_file.rs
src/test/spec/unified_runner/test_runner.rs

Implements the `download_to_stream` method described [here](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#file-download) and the `download_to_stream_by_name` method described [here](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#file-download-by-filename)

RUST-1400 GridFS download methods

---

src/gridfs.rs
src/gridfs/options.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_runner.rs

Implements the remaining API methods defined in the GridFS spec, including the advanced API.

RUST-1401 Additional GridFS API

---

src/gridfs.rs
src/gridfs/upload.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_runner.rs

Implements the `upload_from_stream` and `upload_from_stream_with_id` methods described in this section of the spec: https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#file-upload

RUST-1478 GridFS upload methods

---

etc/update-spec-tests.sh
src/test/spec/json/change-streams/unified/change-streams-clusterTime.json
src/test/spec/json/change-streams/unified/change-streams-clusterTime.yml

RUST-1461
This also updates update-spec-tests.sh to accept a git hash, which I figured was useful to review. The only other changes are just test syncs.

RUST-1461 Sync clustertime change stream tests

---

.evergreen/config.yml
.evergreen/configure-rust.sh
.evergreen/find-crypt_shared.sh
.evergreen/run-csfle-kmip-servers.sh
.evergreen/run-csfle-tests.sh
.gitignore
Cargo.toml
src/client/csfle.rs
src/client/csfle/client_encryption.rs
src/client/csfle/options.rs
src/client/csfle/state_machine.rs
src/client/executor.rs
src/client/mod.rs
src/cmap/conn/command.rs
src/cmap/conn/stream_description.rs
src/hello.rs
src/runtime/process.rs
src/sdam/description/topology/test/sdam.rs
src/test/csfle.rs
src/test/spec/json/client-side-encryption/testdata/encryptedFields.json
src/test/spec/json/client-side-encryption/testdata/key1-document.json
src/test/util/event.rs
src/test/util/failpoint.rs
src/test/util/subscriber.rs

RUST-1386
This adds the remaining prose tests, as well as expanding the Evergreen configuration to cover more cases.  I went with a sparse matrix for testing rather than every permutation, as there didn't seem to be much value in the latter.

RUST-1386 Implement the remainder of the FLE prose tests

---

README.md

RUST-1477
This PR adds a notice to the README that the 1.x version of the driver has reached EOL status and won't receive any more updates. I ended up not adding any compiler warnings or anything since the `compile_warning` macro never got introduced to the language.

RUST-1477 Add 1.x EOL notice

---

src/test/spec/client_side_encryption.rs
src/test/spec/json/testdata/client-side-encryption/encryptedFields.json
src/test/spec/json/testdata/client-side-encryption/key1-document.json

This skips a spec test that requires openssl when that's not enabled, and includes a few accidentally-omitted data files.

minor: fix csfle tests

---

src/client/csfle.rs
src/client/csfle/client_builder.rs
src/client/csfle/client_encryption.rs
src/client/csfle/options.rs
src/client/mod.rs
src/client/options/mod.rs
src/test/csfle.rs
src/test/mod.rs
src/test/spec/unified_runner/operation/csfle.rs
src/test/spec/unified_runner/test_runner.rs

This adds convenience builders for the two entry points (`Client` and `ClientEncryption`), and updates methods on the latter to use the action pattern.

RUST-1536: tidy the client-side encryption API

---

src/lib.rs

minor: improve compile error when `sync` and `tokio-runtime` are enabled

---

.evergreen/feature-combinations.sh
.evergreen/run-csfle-tests.sh
Cargo.toml
src/client/executor.rs
src/client/mod.rs
src/coll/mod.rs
src/coll/options.rs
src/db/mod.rs
src/db/options.rs
src/error.rs
src/lib.rs
src/operation/mod.rs
src/operation/run_command/mod.rs
src/runtime/mod.rs
src/test/csfle.rs
src/test/mod.rs
src/test/spec/mod.rs
src/test/spec/unified_runner/entity.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_file.rs
src/test/spec/unified_runner/test_runner.rs
src/test/spec/v2_runner/mod.rs
src/test/spec/v2_runner/operation.rs
src/test/spec/v2_runner/test_file.rs
src/test/util/event.rs
src/test/util/mod.rs
src/test/util/subscriber.rs

RUST-1487 / RUST-1347
This renames the `csfle` feature to `in-use-encryption-unstable`; this combines the naming guidance of RUST-1487 and the "preview" factor from RUST-1347.  The latter encourages using language-specific conventions, which for Rust maps nicely to "unstable" vs "stabilized".  While only the queryable encryption API needs to be flagged as unstable, I think it'll be valuable to keep the whole encryption API unstable so we have room for iteration based on user feedback.
I didn't rename any of the internal stuff (e.g. `csfle.rs`) because that felt like a lot of churn for little benefit.

RUST-1487 Rename "csfle" to "in-use-encryption-unstable"

---

src/test/spec/json/unified-test-format/valid-pass/observeSensitiveCommands.json
src/test/spec/json/unified-test-format/valid-pass/observeSensitiveCommands.yml

I forgot to sync the changes I made to the unified runner valid pass tests for this ticket, and so these tests are now failing on evergreen against latest.

RUST-1544 sync valid-pass test for observeSensitiveCommands

---

src/results.rs
src/test/mod.rs
src/test/timeseries.rs

Cherry-picking this from the `main` branch for RUST-1584.

RUST-1576 Allow "timeseries"-typed collections in list_collections output (#814)

---

src/client/executor.rs
src/test/spec/sessions.rs

RUST-1069
Previously, retries were handled by a distinct `execute_retry` method; this was an issue for this change because there are two retry cases (connection check out failure and operation failure), and a retry should create an implicit session in the first case but not the second.  This PR changes it to have a loop inside `execute_operation_with_retry`; this makes the handling there a bit more complicated, but removes the `execute_retry` method entirely, and also collapses `ExecutionOutput` into `ExecutionDetails`, so I think it's a net wash on complexity.  Having the loop will also make executing multiple retries easier if/when we get to CSOT.

RUST-1069 Defer implicit session check out until after connection check out

---

src/test/spec/json/command-logging-and-monitoring/logging/unacknowledged-write.json
src/test/spec/json/command-logging-and-monitoring/logging/unacknowledged-write.yml
src/test/spec/trace.rs

This test was added after our implementation. We can't run it since we don't support uancknowledged writes but syncing the file nonetheless to keep us up-to-date.

RUST-1566 Sync (and skip) command logging unacknowledged write test

---

.evergreen/env.sh
src/client/session/test/mod.rs

RUST-1100
This uses a blunt hammer fix: the failure was the cursor immediately ending, so presumably there was still a race between replication and the test logic.  Since the point of the test isn't replication behavior but sessions, this just adds a loop until the cursor has data.

RUST-1100 Fix find_and_getmore_share_session flakiness

---

src/coll/mod.rs

This aims to address https://jira.mongodb.org/browse/RUST-1582 as originally filed as an issue in https://github.com/mongodb/mongo-rust-driver/issues/812.
There was already a member function in the collection object which allowed client access but it was only accessible from within the driver crate. So the only changes needed are to make it externally accessible.

RUST-1582 Expose collection.client() as public

---

.evergreen/check-rustdoc.sh
.evergreen/feature-combinations.sh
Cargo.toml
src/client/auth/mod.rs
src/client/options/mod.rs
src/compression/mod.rs
src/lib.rs

As far as I can tell there's not a great way to test what this is going to look like on docs.rs short of doing a release, but the FLE docs should show up in the same way that the sync docs currently do.

minor: fix documentation of new features

---

src/error.rs

RUST-1574
In some older server versions this field is optional, but we can't change the type signature, so just default it to `""`.

RUST-1574 Default errmsg field to empty string

---

.evergreen/config.yml

RUST-1503
This adds testing against versions back to 4.2 for both crypt_shared and mongocryptd.  Happily, tests passed unmodified.

RUST-1503 Test csfle against older server versions

---

.evergreen/run-csfle-tests.sh
src/client/auth/aws.rs
src/client/auth/mod.rs
src/client/csfle.rs
src/client/csfle/client_encryption.rs
src/client/csfle/options.rs
src/client/csfle/state_machine.rs
src/test/csfle.rs

Cherry-pick from main for the 2.4.0 release.

RUST-1314 Support on-demand AWS credentials for in-use encryption (#831)

---

src/client/options/mod.rs
src/client/options/test.rs

This adds `uuidRepresentation` to `ConnectionString`.
I wasn't sure what to put for the documentation comment, it could probably be cleaned up.

RUST-1607: allow uuidRepresentation in connection string

---

src/cmap/establish/handshake/mod.rs
src/test/spec/faas.rs
src/test/spec/mod.rs

RUST-1501
This implements the new data collection from environment variables and the associated fallback logic to keep the handshake within the size limit.

RUST-1501 Collect FaaS platform metadata

---

.evergreen/MSRV-Cargo.lock
src/client/session/mod.rs
src/error.rs
src/sync/client/session.rs
src/test/spec/json/transactions-convenient-api/README.rst
src/test/spec/json/transactions-convenient-api/callback-aborts.json
src/test/spec/json/transactions-convenient-api/callback-aborts.yml
src/test/spec/json/transactions-convenient-api/callback-commits.json
src/test/spec/json/transactions-convenient-api/callback-commits.yml
src/test/spec/json/transactions-convenient-api/callback-retry.json
src/test/spec/json/transactions-convenient-api/callback-retry.yml
src/test/spec/json/transactions-convenient-api/commit-retry.json
src/test/spec/json/transactions-convenient-api/commit-retry.yml
src/test/spec/json/transactions-convenient-api/commit-transienttransactionerror-4.2.json
src/test/spec/json/transactions-convenient-api/commit-transienttransactionerror-4.2.yml
src/test/spec/json/transactions-convenient-api/commit-transienttransactionerror.json
src/test/spec/json/transactions-convenient-api/commit-transienttransactionerror.yml
src/test/spec/json/transactions-convenient-api/commit-writeconcernerror.json
src/test/spec/json/transactions-convenient-api/commit-writeconcernerror.yml
src/test/spec/json/transactions-convenient-api/commit.json
src/test/spec/json/transactions-convenient-api/commit.yml
src/test/spec/json/transactions-convenient-api/transaction-options.json
src/test/spec/json/transactions-convenient-api/transaction-options.yml
src/test/spec/transactions.rs
src/test/spec/v2_runner/mod.rs
src/test/spec/v2_runner/operation.rs
src/test/spec/v2_runner/test_file.rs

RUST-107
This adds the convenient transactions API and associated tests.  Running the v2 spec tests required quite a bit of refactoring in order to allow recursively running operations within the `withTransaction` operation.

RUST-107 Convenient transactions

---

src/client/csfle/client_encryption.rs
src/db/mod.rs
src/sync/db.rs
src/test/csfle.rs

RUST-1411
While writing up the release notes for 2.5.0, I realize that `create_encrypted_collection` is in the spec as a method on `ClientEncryption`, not (as I'd implemented it) `Database`.  While it makes some sense to be on the latter as a parallel to `create_collection`, since the spec and all other language drivers implement it the other way, I updated us to follow suit.

RUST-1411 Move `create_encrypted_collection` helper to `ClientEncryption`

---

src/client/csfle.rs
src/client/csfle/client_encryption.rs

RUST-1605
As of 1.8.0-alpha1, the `fle2v2` method has been removed and libmongocrypt just defaults to using v2.

RUST-1605 Remove fle2v2 calls

---

.evergreen/config.yml
.evergreen/feature-combinations.sh
.evergreen/run-csfle-mock-azure-imds.sh
.evergreen/run-csfle-tests.sh
Cargo.toml
src/client/auth/mod.rs
src/client/csfle.rs
src/client/csfle/state_machine.rs
src/cmap/establish/handshake/mod.rs
src/cmap/establish/handshake/test.rs
src/cmap/establish/mod.rs
src/cmap/test/integration.rs
src/cmap/test/mod.rs
src/runtime/http.rs
src/runtime/mod.rs
src/sdam/topology.rs
src/test/csfle.rs

RUST-1442
This adds support for fetching on-demand csfle credentials from the Azure IMDS service.  Notably, this requires an HTTP fetch, so this updates the internal `HttpClient` to not be aws auth only; this also means that azure auth has the same restriction as aws auth (i.e. tokio), and is behind a feature flag.
This PR includes the unit tests; integration tests to come in a follow-up PR.

RUST-1442 On-demand Azure KMS credentials

---

.evergreen/azure-kms-test/.gitignore
.evergreen/azure-kms-test/Cargo.toml
.evergreen/azure-kms-test/src/main.rs
.evergreen/config.yml
.evergreen/run-azure-kms-test.sh
src/test/csfle.rs

RUST-1442
This adds the integration tests for on-demand Azure KMS credentials; the failing one is just a normal test since we don't run those on Azure, the passing one is a binary that gets run on an Azure VM.

RUST-1442 Azure KMS integration test

---

.evergreen/config.yml
.evergreen/env.sh
Cargo.toml
src/client/csfle/state_machine.rs
src/runtime/http.rs
src/test/atlas_planned_maintenance_testing/mod.rs
src/test/csfle.rs

This is going to be a slightly messy rebase, so I'm going to hold off on doing that until this PR is approved and I can squash my git history.

RUST-1417 Add support for GCP attached service accounts when using GCP KMS

---

src/test/change_stream.rs

DRIVERS-2617
This adds a PoC for a simple prose test to validate that the driver handles the new `$changeStreamSplitLargeEvent` stage.

DRIVERS-2617 Test splitting of large changestream events

---

.evergreen/config.yml
src/test/spec/sessions.rs

`mongocryptd` doesn't need to be installed for 99% of work on the driver, and this way those tests don't fail in that case if run incidentally (i.e. as part of a full test run).

minor: skip session tests if mongocryptd fails to spawn

---

src/change_stream/mod.rs
src/cursor/common.rs
src/cursor/mod.rs
src/cursor/session.rs

RUST-1358
Now that we're internally passing around `RawDocument` rather than the deserialized type, we don't need to carry around the final type for our internal cursor implementation bits, and in turn we don't need the `Sync + Send + Unpin` constraints on that type.
I think there's further opportunity for cleaning up the implementation, but that won't have any user-facing benefit, so I've filed RUST-1676 to track that.

RUST-1358 Remove most type constraints on cursor values

---

src/cmap/conn/mod.rs
src/hello.rs

ServerId is assigned to ConnectionId here: [https://github.com/mongodb/mongo-rust-driver/blob/main/src/cmap/establish/handshake/mod.rs#L457](https://github.com/mongodb/mongo-rust-driver/blob/main/src/cmap/establish/handshake/mod.rs#L457 ). To fix the int32 overflow issue, I added a new ServerId int64 value.

RUST-1571 Update ServerId to be int64

---

src/concern/test.rs
src/db/mod.rs
src/operation/run_command/mod.rs
src/sdam/description/topology/mod.rs
src/selection_criteria.rs
src/test/spec/json/run-command/README.rst
src/test/spec/json/run-command/unified/runCommand.json
src/test/spec/json/run-command/unified/runCommand.yml
src/test/spec/json/run-command/unified/runCursorCommand.json
src/test/spec/json/run-command/unified/runCursorCommand.yml
src/test/spec/mod.rs
src/test/spec/run_command.rs
src/test/spec/unified_runner/matcher.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_file.rs

1. Removed `write_concern` and `read_concern` from RunCommand API to update with the new specification: https://github.com/mongodb/specifications/commit/ab66eaf6f7e2bbeb5218672bebaf5118faf8209c
2. Added in new spec tests for RunCommand

RUST-1636 Add RunCommand Test Specification

---

src/db/options.rs
src/index/options.rs
src/selection_criteria.rs
src/serde_util.rs
src/test/spec/collection_management.rs
src/test/spec/json/collection-management/modifyCollection-errorResponse.json
src/test/spec/json/collection-management/modifyCollection-errorResponse.yml
src/test/spec/json/collection-management/timeseries-collection.json
src/test/spec/json/collection-management/timeseries-collection.yml
src/test/spec/mod.rs

The drivers ticket description only details a test sync, but the new tests were using options we hadn't implemented yet.

RUST-1604 Add custom bucketing fields to timeseries options

---

src/coll/options.rs
src/db.rs
src/db/options.rs
src/operation.rs
src/operation/run_cursor_command.rs
src/results.rs

added operation `RunCursorCommand` (spec: https://github.com/mongodb/specifications/blob/c09f979ad296400552a98c9b784197ec648c2096/source/run-command/run-command.rst#runcursorcommand)
- implemented Operation which uses default RunCommand behavior for every method but handle_response

RUST-1588: Add RunCursorCommand

---

.config/nextest.toml
.evergreen/cargo-test.sh
.evergreen/config.yml
.evergreen/install-dependencies.sh
.evergreen/run-atlas-tests.sh
.evergreen/run-aws-tests.sh
.evergreen/run-connection-string-tests.sh
.evergreen/run-csfle-tests.sh
.evergreen/run-oidc-tests.sh
.evergreen/run-plain-tests.sh
.evergreen/run-serverless-tests.sh
.evergreen/run-tests.sh
.evergreen/run-x509-tests.sh
src/change_stream.rs
src/lib.rs

RUST-1674
This switches to using `cargo-nextest`, with the immediate benefit of removing the need for the unstable output options and corresponding Rust version pinning.  Because `cargo-nextest` runs each test in its own process, our existing test lock no longer works; as a workaround, I've set `cargo-nextest` to only run one test at a time.  Future work for which I've filed tickets:
* RUST-1721 Use test profiles to regain parallelism
* RUST-1722 Remove now-defunct test locks
* RUST-1723 Take advantage of cargo-nextest flaky test detection

RUST-1674 Use cargo-nextest as test runner

---

src/cursor/session.rs
src/test/cursor.rs

Hello there,
when using the transaction API, I encountered unconditional panic and also panic while dropping in `SessionCursor::with_type`. The problem occurs because the `.state` is moved into new cursor and subsequently, `.unwrap()` is called on it when marking it exhausted and also when checking for exhaustion. This is the minimal code change to fix this problem

RUST-1719 Fix panic after `SessionCursor::with_type` is called

---

src/coll.rs
src/coll/options.rs
src/operation/insert.rs
src/operation/insert/test.rs
src/test/coll.rs
src/test/spec/unified_runner/test_file.rs

…`find_one_and_replace_common`
This was a solution proposed by @isabelatkinson for the problem described in the following [PR](https://github.com/mongodb/mongo-rust-driver/pull/883) and the [Task](https://jira.mongodb.org/browse/RUST-1687)
Regards,
Maicon Pavi.

RUST-1687 Add `human_readable_serialization` option to `Collection`

---

src/cursor.rs
src/cursor/common.rs
src/cursor/session.rs
src/test/spec/run_command.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_runner.rs

This PR implements the `IterateOnce` unified test operation and unskips the "does not close the cursor when receiving an empty batch" `run_cursor_command` test. This operation required adding a test-only `try_advance` method to `Cursor` and `SessionCursor`, which only performs one getMore rather than looping until the buffer has been refilled. I considered adding this method to the public API, but chose not to for a few reasons:
- No users have asked for this functionality.
- Depending upon what we decided the method should return, we might need to add a new type (`AdvanceResult`) to our API as well.
- The existence of `advance` and `try_advance` might be confusing to users.
If we do receive requests for this functionality we can further discuss API and consider making it public then.

RUST-1588 Implement `IterateOnce` unified test runner operation

---

src/gridfs.rs

RUST-1743
This fixes the ``Chunk.n`` and ``FilesCollectionDocument.chunk_size_bytes`` to serialize as ``i32`` rather than ``i64``.  Happily, deserialization will accept either, so this is backwards-compatible.

RUST-1743 Fix gridfs numeric type serialization

---

.config/nextest.toml

This removes the need to include it on the command line for local runs.

minor: set test-threads in default nextest profile

---

src/gridfs/upload.rs

This works around https://github.com/async-rs/async-std/issues/1066; tokio doesn't have this issue but the workaround works either way.

RUST-1698 Fix reading gridfs chunks from async-std file stream

---

.evergreen/benchmarks.yml

RUST-1698
Some of the benchmark runs fail, and have been failing for quite some time; fix for that to come in a follow-up PR.

RUST-1698 Use standardized os and db version for benchmarks

---

src/cursor/common.rs
src/test/cursor.rs

RUST-1757
Looks like this broke as part of a refactor a few weeks ago, so the only release it's live in is 2.7.0-beta :)

RUST-1757 Fix final cursor batch handling

---

src/cursor/common.rs
src/test/cursor.rs

Cherry-pick from https://github.com/mongodb/mongo-rust-driver/pull/951.

RUST-1757 Fix final cursor batch handling (#951)

---

Cargo.toml
src/operation/find_and_modify.rs
src/test/client.rs

Hello,
I found an inconsistency in the way mongo documents are deserialized when using `serde(with)`  and `find_one_and_delete`. My fix might nor be ideal because it breaks
```
< operation::find_and_modify::test::handle_no_value_delete                                                                                                                                                                                    
< operation::find_and_modify::test::handle_no_value_replace                      
< operation::find_and_modify::test::handle_no_value_update
```
The tests no longer return `Err(_)` but just `Ok(None)`. I am not sure how I can assert that Field is present but can be null, when deserializing `Option<T>` and could not find anything either.
I added a tests to verify my changes fix the …

fixing the find or delete serde inconsistency

---

Cargo.toml
src/operation/find_and_modify.rs
src/test/client.rs

Cherry-pick from https://github.com/mongodb/mongo-rust-driver/pull/948.

fixing the find or delete serde inconsistency (#948)

---

src/coll.rs
src/coll/options.rs

Cherry-pick from https://github.com/mongodb/mongo-rust-driver/pull/957.

RUST-1763 deprecate CollectionOptions::human_readable_serialization (#957)

---

src/coll/options.rs
src/test/spec/unified_runner/test_file.rs

Cherry-pick from https://github.com/mongodb/mongo-rust-driver/pull/960.

minor: fix deprecation warnings (#960)

---

src/client.rs
src/client/executor.rs
src/sdam/description/topology/server_selection.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/test/spec/retryable_reads.rs
src/test/spec/retryable_writes.rs

RUST-935
I opted to introduce the `SelectionRetry` wrapper so that the actual details of what it is and how it's used only need to be known within `attempt_to_select_server` - callers just need to preserve it and pass it back in.  I did consider making this part of `SelectionCriteria`, but that would have been a pretty major refactoring since that would have to move from the current `enum` to a `struct` with a "kind" enum.

RUST-935 direct retries to different mongos

---

.evergreen/cargo-test.sh
src/test/util.rs

RUST-1749
This is a little complex because I had to use two tricks here:
* When running attached to a terminal (i.e. local testing), writing directly to `/dev/tty` will bypass the indirection.
* However, there's no attached terminal when running on Evergreen, so in that case it creates a temporary file and runs a background task tailing that file before running the tests.

RUST-1749 Update log_uncaptured to bypass cargo nextest

---

src/client.rs
src/id_set.rs

RUST-1779
There turned out to be two issues:
* a straightforward bug where if a command generating a cleanup item finished quickly, that (inert) cleanup item was never removed from the list
* incrementing an id to generate a hashmap key is basically pessimal behavior for hashmaps
To fix the second I switched the storage over to a vec with a secondary list of free indices for efficient removal.  The `generation` tag ensures that a given `Id` won't remove a value that's re-used that slot in the vec.  While the storage vec is never shrunk, the reuse of indices means it'll only grow up to capacity for peak concurrent cleanup operation execution.

RUST-1779 Fix a memory leak in cleanup tracking

---

src/cursor.rs
src/cursor/common.rs
src/cursor/session.rs

RUST-1676 Simplify `GenericCursor` by refactoring the `GetMoreProvider` trait into a generic struct

---

.config/nextest.toml
src/client/options.rs
src/client/options/test.rs
src/sdam.rs
src/sdam/description/topology.rs
src/sdam/description/topology/server_selection.rs
src/sdam/description/topology/server_selection/test.rs
src/sdam/srv_polling.rs
src/sdam/srv_polling/test.rs
src/sdam/topology.rs
src/srv.rs
src/test/spec/initial_dns_seedlist_discovery.rs
src/test/spec/json/uri-options/srv-options.json
src/test/spec/json/uri-options/srv-options.yml
src/test/spec/trace.rs

RUST-933
Pretty straightforward.  The shuffling needs to be in two places (initial host discovery and polling), unfortunately, because the logic at those two places is a bit different.

RUST-933 Add support for the srvMaxHosts option

---

README.md

This PR partially resolves RUST-1775. The link on README.md is updated to point to the new documentation site hosted on mongodb.com.

RUST-1775 update link on README to mongodb.com

---

.evergreen/run-csfle-tests.sh

RUST-1806
We hadn't implemented this bit of the tests yet when the ticket to convert to the new shell scripts was done, so I guess this is the moral equivalent of a race condition use after free?

RUST-1806 Fix in use encryption tests

---

.evergreen/config.yml
.evergreen/env.sh
.evergreen/run-aws-tests.sh

Removes all uses of the legacy shell by migrating to the new AWS scripts in drivers-evergreen-tools. Also completes RUST-1777 by upgrading to Ubuntu 20.04 (the new arn is no longer relevant now that we're using the secrets manager).

RUST-1525 Update AWS tests to use new scripts

---

.evergreen/config.yml

This updates the serverless tests to use the aws secret manager (which includes `SERVERLESS_REGION`).

RUST-1831 Use secret manager for serverless tests

---

Cargo.toml
src/operation/update.rs
src/sdam/description/topology.rs

AFAIK, socket2's
```
rust-version  = "1.63" 
```
matchs the driver's 1.64+

chore: bump `socket2` to 0.5

---

src/hello.rs
src/test.rs
src/test/hello.rs

RUST-1841
It turns out that when we implemented RUST-1571 we missed that the value could be a double as well as an int64.
I'll cherry-pick this to `main` as well.

RUST-1841 Allow double-valued connectionIds

---

.evergreen/config.yml
.evergreen/generate-uri.sh

RUST-1839 / RUST-1838
Since they're not patchable, [here's](https://spruce.mongodb.com/version/65ce5ae3a4cf473f1634d93e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) a run with OIDC and [here's](https://spruce.mongodb.com/version/65ce62a8850e61402789c00b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) one with serverless.

RUST-1839 Avoid logging secrets when running OIDC or serverless tests

---

.evergreen/aws-lambda-test/mongodb/src/main.rs
src/client/options.rs
src/cmap.rs
src/cmap/establish/handshake.rs
src/sdam/monitor.rs
src/test/spec/json/server-discovery-and-monitoring/README.rst
src/test/spec/json/server-discovery-and-monitoring/unified/pool-cleared-error.yml
src/test/spec/json/server-discovery-and-monitoring/unified/serverMonitoringMode.json
src/test/spec/json/server-discovery-and-monitoring/unified/serverMonitoringMode.yml
src/test/spec/json/uri-options/sdam-options.json
src/test/spec/json/uri-options/sdam-options.yml
src/test/spec/unified_runner/matcher.rs
src/test/spec/unified_runner/test_event.rs
src/test/spec/unified_runner/test_file.rs
src/test/spec/unified_runner/test_runner.rs
src/test/util/event.rs

RUST-1631
The core change is pretty simple - add some behavior to switch back to polling when FaaS is detected - but there's a lot of stuff around that (tests, URI config, etc.)

RUST-1631 Always use polling monitoring when running in a FaaS environment

---

manual/src/encryption.md
src/action.rs
src/action/csfle.rs
src/action/csfle/create_data_key.rs
src/action/csfle/create_encrypted_collection.rs
src/action/csfle/encrypt.rs
src/client/csfle/client_encryption.rs
src/client/csfle/client_encryption/create_data_key.rs
src/client/csfle/client_encryption/encrypt.rs
src/test/csfle.rs
src/test/spec/unified_runner/operation/csfle.rs

RUST-1829
The CSFLE API already used a fluent pattern, but it wasn't using the common machinery we built for the rest of the client.  There's lots of bits shuffling around here but no functional changes.

RUST-1829 Update csfle fluent API to be consistent with the rest of the driver

---

src/db.rs

https://jira.mongodb.org/browse/RUST-1856
Expose existing `Database::client` method as `pub`.

RUST-1856 expose Database::client

---

.evergreen/config.yml
src/client/auth.rs
src/client/auth/oidc.rs
src/client/executor.rs
src/error.rs
src/test/spec/oidc.rs

This ended up much easier than I expected, thanks to how well the rust driver is architected

RUST-1663: Implement and enable reauthentication for OIDC

---

src/bson_util.rs
src/checked.rs
src/client/options.rs
src/cmap/conn/wire/message.rs
src/collation.rs
src/error.rs
src/gridfs.rs
src/gridfs/upload.rs
src/hello.rs
src/lib.rs
src/operation.rs
src/operation/get_more.rs
src/operation/insert.rs
src/sdam/description/topology/server_selection.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/sdam/description/topology/test.rs
src/serde_util.rs
src/test.rs

RUST-1881
This vendors the `Checked` type from https://github.com/zeta12ti/Checked, minus the `num_traits` support, plus a few conveniences for our specific error type, and uses it to check both integer conversions and integer arithmetic for particularly sensitive values like buffer sizes.  The guidelines I used for this:
* at function boundaries, sizes should be represented as `usize`
* within a function, sizes should be `Checked<usize>` starting at the earliest possible point (ideally, initialization from a constant or single value), and persisting as late as possible so that all arithmetic is also checked.
* deadlines (number of seconds/millis) can saturate in conversion
* where context doesn't provide an easy way to propagate a `Result`, `unwrap` is used on the grounds that a crash is …

RUST-1881 Check integer conversions

---

src/test/coll.rs
src/test/spec/unified_runner/test_runner.rs
src/test/util.rs

RUST-1855
This fixes some flaky unified tests; note that we'll still see failures in legacy tests until RUST-817 is done.

RUST-1855 Propagate cluster time for unified tests

---

action_macro/Cargo.toml
action_macro/src/lib.rs
src/action.rs
src/action/aggregate.rs
src/action/count.rs
src/action/create_collection.rs
src/action/create_index.rs
src/action/csfle/create_data_key.rs
src/action/csfle/encrypt.rs
src/action/delete.rs
src/action/distinct.rs
src/action/drop.rs
src/action/drop_index.rs
src/action/find.rs
src/action/find_and_modify.rs
src/action/insert_many.rs
src/action/insert_one.rs
src/action/list_collections.rs
src/action/list_databases.rs
src/action/list_indexes.rs
src/action/perf.rs
src/action/replace_one.rs
src/action/run_command.rs
src/action/session.rs
src/action/update.rs
src/action/watch.rs

RUST-1512
For return types in code that include generic parameters, rustdoc will generate output that links to both the generic type and the parameter types; however, when using bracketed comment links, the generic parameters are ignored.  This means that the action documentation for what `await` or `run` returns is less useful than previously, especially in cases of deeply nested types like `Result<ChangeStream<ChangeStreamEvent<Document>>>`.  For particularly gnarly cases I attempted to manually link components but this is fiddly, error-prone, and easy to forget.
This PR addresses that by introducing a helper `#[deeplink]` attr macro that will look for docstring links of the form `d[...]` and render them with all component types individually linked.  The core trick is that `/// stuff` …

RUST-1512 Better links for action return types

---

Cargo.toml
src/action/find_and_modify.rs
src/action/insert_many.rs
src/action/insert_one.rs
src/action/replace_one.rs
src/coll.rs
src/coll/options.rs
src/serde_util.rs
src/test/coll.rs
src/test/spec/unified_runner/test_file.rs

RUST-1764
This goes along with https://github.com/mongodb/bson-rust/pull/471; I'll remove the `[patch]` pointing at my repo when that goes in.

RUST-1764 Drop human_readable options in favor of HumanReadable

---

action_macro/src/lib.rs
src/action.rs
src/action/csfle/create_data_key.rs

RUST-1860
The hammer of `proc_macro` looked like a good fit for this nail as well, since it means that the `option_setters!` macro can just have special handling for the specific types rather than having to handcode it for every action.

RUST-1860 Accept ergonomic conversions for specific option types

---

src/client/session/test.rs
src/client/session/test/causal_consistency.rs
src/cmap/test.rs
src/concern/test.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/sdam/description/topology/test/sdam.rs
src/sdam/test.rs
src/test/change_stream.rs
src/test/client.rs
src/test/coll.rs
src/test/csfle.rs
src/test/cursor.rs
src/test/db.rs
src/test/index_management.rs
src/test/spec/connection_stepdown.rs
src/test/spec/retryable_reads.rs
src/test/spec/retryable_writes.rs
src/test/spec/sessions.rs
src/test/spec/transactions.rs
src/test/spec/v2_runner.rs
src/test/spec/write_error.rs
src/test/util.rs
src/test/util/event.rs

RUST-1890
This makes `EventClient` the sole way for tests to track events, and the builder the sole way to construct an `EventClient`.
I did attempt the parameterized `TestClient` path but the type machinery ended up more complicated there than it seemed like it was worth; the approach in this PR also has the advantage that the event handling code is nicely separated from the base `TestClient` code.

RUST-1890 Consolidate test event monitoring and client construction

---

src/error.rs

RUST-1913
The behavior of `#[non_exhaustive]` for a tuple variant is pretty surprising - it prevents matching on the variant at all, even with a wildcard for the body (see https://github.com/mongodb/mongo-rust-driver/issues/1071).  This removes that tag from the `GridFs` variant, which is consistent with our other simple wrapper variants (`BulkWrite`, `Command`, etc.).

RUST-1913 Remove non_exhaustive from ErrorKind::GridFs

---

src/db/options.rs
src/test/db.rs

#1003
I wasn't able to reproduce this locally (seems like an Atlas-only issue), so this fix includes a deserialization test contributed by the user for a boolean value and a test of `list_collections` to ensure we can still deserialize from options properly.
This includes the changes from #1076; I'll rebase once that's merged.

RUST-1819 Fix `list_collections` on Atlas for clustered collections

---

.evergreen/check-clippy.sh
.evergreen/check-semgrep.sh
.evergreen/config.yml
.semgrepignore
src/client/auth/scram.rs
src/runtime/tls_rustls.rs

RUST-1920
This switches from clippy to semgrep as the provider for SARIF reports.  The latter flagged a few spots in the driver code but both of them are false positives (support for the user requesting non-ideal options, basically) so I added comments to suppress those.

RUST-1920 Use semgrep to generate SARIF reports

---

.evergreen/release-danger-do-not-run-manually.sh
.evergreen/release-fetch-tag.sh
.evergreen/releases.yml

RUST-1921
This splits the "checkout git tag" part from the main release script to enable a later PR to sign/trace the release artifacts.  It also adds a way to enable dry-run mode for releases run through evergreen for ease of testing.

RUST-1921 Minor release script refactor

---

sbom.json

RUST-1935
Since the Rust driver doesn't bundle any dependencies, our SBOM is empty.

RUST-1935 Add an empty sbom

---

src/action/bulk_write.rs
src/action/insert_many.rs
src/action/insert_one.rs
src/error.rs
src/operation.rs
src/operation/bulk_write.rs
src/operation/delete.rs
src/operation/insert.rs
src/operation/update.rs
src/sdam/description/topology/test/sdam.rs
src/test/bulk_write.rs
src/test/coll.rs
src/test/spec/trace.rs
src/test/spec/unified_runner/test_file.rs

Main changes here:
- `ErrorKind::BulkWrite` -> `ErrorKind::InsertMany`
- `BulkWriteFailure` -> `InsertManyError`
- `BulkWriteError` -> `IndexedWriteError`
- `ErrorKind::ClientBulkWrite` -> `ErrorKind::BulkWrite`
- `ClientBulkWriteError` -> `BulkWriteError`
The first three changes were on types only used for the `insert_many` API.

RUST-1857 Clean up names for multi-write errors

---

src/action/bulk_write.rs
src/client/options/bulk_write.rs
src/test/bulk_write.rs
src/test/spec/unified_runner/operation/bulk_write.rs

This also has the changes from #1103, filtering by the last commit will show the relevant changes for this PR.

RUST-1858 Add builders for bulk write models

---

src/client/session/test.rs
src/client/session/test/causal_consistency.rs
src/test/change_stream.rs
src/test/coll.rs
src/test/cursor.rs
src/test/spec/retryable_reads.rs
src/test/spec/retryable_writes.rs
src/test/spec/write_error.rs
src/test/util/event.rs
src/test/util/event_buffer.rs

RUST-1888
`get_command_events` and `get_successful_command_execution` both had surprising mutation of the underlying event buffer that was only useful in a few niche cases; this updates them to be immutable.  The few places that needed the mutation (running tests in a loop on a shared client, interleaving tests and event assertions) now use an explicit buffer clear.

RUST-1888 Remove incidental mutability from EventBuffer

---

src/operation.rs
src/operation/bulk_write.rs
src/test/bulk_write.rs

Attempting to call `bulk_write` on a 7.0 server currently yields the following error:
```
Error: Error { kind: Command(CommandError { code: 40415, code_name: "Location40415", message: "BSON field 'bulkWrite.errorsOnly' is an unknown field.", topology_version: None }), labels: {}, wire_version: Some(21), source: None }
```
This PR adds a more informative error to avoid confusion if/when users attempt to use this feature with 7.0.
This is a temporary fix; once the server error is improved, we can remove this check ([SERVER-91171](https://jira.mongodb.org/browse/SERVER-91171)).

minor: return an error if `bulk_write` is called on an unsupported server

---

.evergreen/check-semgrep.sh
.gitignore
.semgrepignore
src/client/auth/scram.rs
src/runtime/tls_rustls.rs

RUST-1920
The requirements for static analysis include annotating findings with the MongoDB risk rating; this PR adds code comments that will be included in the semgrep report with the appropriate rating for the two current findings.
Additionally, the report needs to be "archived in some internal repository", and _not_ included as a release artifact, so I updated the `check-semgrep.sh` script to work when run interactively.  If it makes sense to you, I'll update the release instructions to include uploading a report to a team Drive folder.

RUST-1920 Annotate sarif report with mongodb ratings

---

.evergreen/create-ssdlc-compliance-report.sh
.evergreen/releases.yml
.evergreen/ssdlc-compliance-report-template.md

Uses the minimal format outlined here: https://gist.github.com/rtimmons/8253d1dfcc5f233bdb2d9c73b8e5c129
Dry run release patch with file: https://spruce.mongodb.com/version/6668c6e0b542fb0007a803b2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

RUST-1924 Generate and upload SSDLC compliance report

---

.evergreen/config.yml
.evergreen/run-atlas-tests.sh
src/test/atlas_connectivity.rs

RUST-1971 / RUST-1975
The fixes for both were to pull credentials from the secrets manager rather than using static evergreen config values.  [Here's](https://spruce.mongodb.com/task/mongo_rust_driver_atlas_connectivity_test_atlas_connectivity_patch_90d788af2763d869b12f889eff8e681ecf7d1cec_666b10fce7646b000759d3ae_24_06_13_15_32_17?execution=0&sortBy=STATUS&sortDir=ASC) the passing run for these.

RUST-1971 / RUST-1975 Update Atlas connectivity credentials

---

etc/wasmedge/.cargo/config.toml
etc/wasmedge/.gitignore
etc/wasmedge/Cargo.toml
etc/wasmedge/README.md
etc/wasmedge/src/main.rs
src/client/auth/oidc.rs
src/runtime/stream.rs

RUST-1973
It turns out that the Rust driver does work on the WasmEdge runtime, at least enough for a very simple example program.  I had to disable setting TCP keepalive, but my understanding from reading the [DRIVERS ticket](https://jira.mongodb.org/browse/DRIVERS-383) that introduced it is that it's there to help long-running client software be resilient to server crashes and isn't strictly critical for general driver use.
The other big caveat is that this relies on forked versions of `tokio` and `socket2` for WasmEdge support.  That's not unique to the MongoDB driver, though, the [mysql example](https://github.com/second-state/microservice-rust-mysql) has the same requirement.

RUST-1973 Example client usage targeting WasmEdge

---

.evergreen/ssdlc-compliance-report-template.md

RUST-1955
Link to the drivers summary as our security testing report.  This also updates the language for the process document so the TODO isn't in the rendered view.

RUST-1955 Link to security report

---

src/cmap/establish.rs
src/test/spec.rs
src/test/spec/handshake.rs
src/test/spec/unified_runner/test_runner.rs

RUST-1846
The specification says to mock the server response; Rust is bad at mocking things, I think what I've done here is the most reasonable moral equivalent.

RUST-1846 Test that `saslSupportedMechs` can contain arbitrary strings

---

.evergreen/config.yml
.evergreen/generate-tasks/src/main.rs
.evergreen/suite-tasks.yml
README.md
src/sdam/description/server.rs
src/test/spec/json/server-discovery-and-monitoring/README.rst
src/test/spec/json/server-discovery-and-monitoring/rs/compatible.json
src/test/spec/json/server-discovery-and-monitoring/rs/compatible.yml
src/test/spec/json/server-discovery-and-monitoring/rs/compatible_unknown.json
src/test/spec/json/server-discovery-and-monitoring/rs/compatible_unknown.yml
src/test/spec/json/server-discovery-and-monitoring/sharded/compatible.json
src/test/spec/json/server-discovery-and-monitoring/sharded/compatible.yml
src/test/spec/json/server-discovery-and-monitoring/single/compatible.json
src/test/spec/json/server-discovery-and-monitoring/single/compatible.yml
src/test/spec/json/server-discovery-and-monitoring/single/too_old_then_upgraded.json
src/test/spec/json/server-discovery-and-monitoring/single/too_old_then_upgraded.yml

RUST-1821
The driver ticket includes
> Cleanup/refactor any code that isn't needed anymore (code needed to support server version 3.6)
I took a look around the driver code and didn't find anything in particular that special cases 3.6 or <4.0.

RUST-1821 EOL support for 3.6

---

src/action/aggregate.rs
src/test/db.rs

RUST-1982
We accidentally overspecialized the impls here, meaning both `aggregate(..).session(..).with_type::<T>()` and `aggregate(..).with_type::<T>().session(..)` would fail to compile for slightly different reasons.

RUST-1982 Fix aggregate with_type with explicit session

---

migration-3.0.md

This only had a perfunctory mention in the "Future-proof Features" section, but that wasn't very descriptive and was easy to miss (e.g. #1152).

minor: update migration guide with bson-* feature removal

---

src/sdam/topology.rs
src/test/spec/json/server-discovery-and-monitoring/unified/loadbalanced-emit-topology-changed-before-close.json
src/test/spec/json/server-discovery-and-monitoring/unified/loadbalanced-emit-topology-changed-before-close.yml
src/test/spec/json/server-discovery-and-monitoring/unified/logging-loadbalanced.json
src/test/spec/json/server-discovery-and-monitoring/unified/logging-loadbalanced.yml
src/test/spec/json/server-discovery-and-monitoring/unified/replicaset-emit-topology-changed-before-close.json
src/test/spec/json/server-discovery-and-monitoring/unified/replicaset-emit-topology-changed-before-close.yml
src/test/spec/json/server-discovery-and-monitoring/unified/sharded-emit-topology-changed-before-close.json
src/test/spec/json/server-discovery-and-monitoring/unified/sharded-emit-topology-changed-before-close.yml
src/test/spec/json/server-discovery-and-monitoring/unified/standalone-emit-topology-changed-before-close.json
src/test/spec/json/server-discovery-and-monitoring/unified/standalone-emit-topology-changed-before-close.yml
src/test/spec/unified_runner/matcher.rs
src/test/spec/unified_runner/test_event.rs

RUST-1791
We were already publishing an event, just needed to update the topology type and add support for checking it in the unified runner.

RUST-1791 Publish an event changing topology state to unknown before closing

---

src/coll/options.rs

Copies some more language from the spec for this option; we got a user question about this.

minor: improve documentation for `show_record_id` option

---

src/test/spec.rs
src/test/spec/json/read-write-concern/README.rst
src/test/spec/json/read-write-concern/operation/default-write-concern-2.6.json
src/test/spec/json/read-write-concern/operation/default-write-concern-2.6.yml
src/test/spec/json/read-write-concern/operation/default-write-concern-3.2.json
src/test/spec/json/read-write-concern/operation/default-write-concern-3.2.yml
src/test/spec/json/read-write-concern/operation/default-write-concern-3.4.json
src/test/spec/json/read-write-concern/operation/default-write-concern-3.4.yml
src/test/spec/json/read-write-concern/operation/default-write-concern-4.2.json
src/test/spec/json/read-write-concern/operation/default-write-concern-4.2.yml
src/test/spec/read_write_concern.rs
src/test/spec/read_write_concern/connection_string.rs
src/test/spec/read_write_concern/operation.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/v2_runner.rs

With this change, the CSFLE tests are the only remaining tests that use the v2 runner 🙂 Unfortunately we're using some of the v2 machinery for other tests, so we can't put the whole module behind the `in-use-encryption-unstable` feature flag.

RUST-1879 Convert read/write concern operation tests to unified format

---

benchmarks/Cargo.toml
benchmarks/src/bench.rs
benchmarks/src/bench/find_many.rs
benchmarks/src/bench/find_one.rs
benchmarks/src/bench/gridfs_download.rs
benchmarks/src/bench/gridfs_multi_download.rs
benchmarks/src/bench/gridfs_multi_upload.rs
benchmarks/src/bench/gridfs_upload.rs
benchmarks/src/bench/insert_many.rs
benchmarks/src/bench/insert_one.rs
benchmarks/src/bench/json_multi_export.rs
benchmarks/src/bench/json_multi_import.rs
benchmarks/src/bench/run_command.rs
benchmarks/src/fs.rs

RUST-1902
When I looked to sanity check that https://github.com/mongodb/bson-rust/pull/483 hadn't caused a regression I discovered to my dismay that the whole benchmark suite has been broken since 3.0 :(
This PR fixes compilation, but the actual server-connecting benchmarks are still broken, I filed RUST-1997 for that.

RUST-1902 Fix benchmarks for client 3.0 API

---

README.md

I also removed a bunch of whitespace from the table that wasn't needed for rendering and (IMO) made it harder to read in text.

minor: add compat-3-0-0 to features table

---

.evergreen/benchmarks.yml

RUST-1997
Passing run [here](https://spruce.mongodb.com/version/66aa826b58c08f00070bf7ef/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) (except for gridfs on a sharded deployment, for which I've filed RUST-2010).

RUST-1997 Fix evergreen benchmarks config

---

deny.toml

RUST-2012
A bunch of fields had been deprecated for a while and became hard errors.  Turns out we could drop them all from the config because the behavior sans field is now what we'd been setting (i.e. deny all the things).

RUST-2012 Fix cargo deny configuration

---

benchmarks/src/bench/run_command.rs
benchmarks/src/main.rs

RUST-1994
I want to make sure that implementing the new connection routine there's no performance regression; this adds a benchmark that includes the client connection time in the measurement.
[This](https://spruce.mongodb.com/version/66acf77d9608260007ce6132/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) is a benchmark run with these changes.
cargo-deny failure is unrelated.

RUST-1994 Add a benchmark for client connection

---

src/runtime/stream.rs

RUST-1994
This adapts the implementation from the [`happy-eyeballs`](https://crates.io/crates/happy-eyeballs) crate rather than using it directly to preserve some stream initialization that didn't fit in that crate and better match our error handling.
Benchmarks are within noise:
* [pre-change](https://parsley.mongodb.com/evergreen/mongo_rust_driver_benchmarking_driver_benchmarks__topology~standalone_os~rhel90_dbx_perf_large_benchmark_driver_66967e6134c98e9503f239b56ecd444ee9b7f215_24_08_06_15_09_06/0/task?bookmarks=0,2677&shareLine=2243): `TEST: Run Command (cold start) -- Score: 0.197 MB/s, Median Iteration Time: 0.659s`
* [post-change](https://parsley.mongodb.com/evergreen/mongo_rust_driver_benchmarking_driver_benchmarks__topology~standalone_os~rhel90_dbx_perf_large_benchmark_driver_pat …

RUST-1994 Implement happy eyeballs for TCP connection

---

.evergreen/config.yml
.evergreen/run-csfle-tests.sh
.evergreen/run-sync-tests.sh
src/error.rs
src/test/csfle.rs
src/test/spec/v2_runner/csfle.rs

RUST-2008
The "almost" here is the serverless tests, which are already failing so there's no way to test if edits here would work :(  Filed RUST-2016 for that.
Passing runs for the non-patchable variants:
* [search index](https://spruce.mongodb.com/version/66bd01bb138cb1000799558a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
* [aws lambda](https://spruce.mongodb.com/version/66be25c90c608400077d709c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

RUST-2008 Remove almost all uses of `add_expansions_to_env`

---

.evergreen/run-csfle-tests.sh
src/client/session/test.rs
src/cmap/test.rs
src/cmap/test/integration.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/sdam/description/topology/test/sdam.rs
src/sdam/test.rs
src/test/client.rs
src/test/coll.rs
src/test/csfle.rs
src/test/spec/retryable_reads.rs
src/test/spec/retryable_writes.rs
src/test/spec/sdam.rs
src/test/spec/sessions.rs
src/test/spec/trace.rs
src/test/spec/unified_runner/entity.rs
src/test/spec/unified_runner/test_runner.rs
src/test/util/event_buffer.rs
src/test/util/trace.rs

RUST-1425
I've spent some time trying various approaches here, and I've come to the conclusion that the status quo is good, actually.
The status quo:
* `EventBuffer`: a vector of timestamped events, with utilities for registering with a `Client` and fetching subsets of events (e.g. `CommandStarted`).
* `EventSubscriber`: a streaming view of events in an `EventBuffer`, with utilities for watching for events matching predicates.
Some approaches I've tried to boil this down to a single unified handler:
* Remove `EventSubscriber` entirely, convert all tests using it to check assumptions post-facto.  This would be an _enormous_ amount of work and there are quite a few tests that (subjectively) are easier to follow with the streaming approach.  Also, some tests use values from earlier events in …

RUST-1425 Clarify test event handling

---

README.md

RUST-1795
This adds a note that the pre-1.0 `mongocrypt` re-export shouldn't be considered to be stable.
I did do a once-over to see if there are any areas of particularly high risk and the short answer is it's really hard to tell with an API that wraps C ☹️  Anything that currently uses constant string values in C to represent an enum ([`Algorithm`](https://docs.rs/mongocrypt/latest/mongocrypt/ctx/enum.Algorithm.html) for example) could change in the C API to have semi-structured data the way KMS providers did.  There are also functions in C that accept a binary buffer where the contents expected could change arbitrarily.

RUST-1795 Add an [in]stability note for mongocrypt

---

.evergreen/cargo-test.sh
.evergreen/config.yml
.evergreen/fetch-drivers-tools.sh
.evergreen/run-atlas-tests.sh
.evergreen/run-aws-tests.sh
.evergreen/run-connection-string-tests.sh
.evergreen/run-csfle-tests.sh
.evergreen/run-plain-tests.sh
.evergreen/run-search-index-test.sh
.evergreen/run-serverless-tests.sh
.evergreen/run-sync-tests.sh
.evergreen/run-tests.sh
.evergreen/run-x509-tests.sh
src/test/spec/json/client-side-encryption/legacy/fle2v2-Rangev2-Compact.json
src/test/spec/json/client-side-encryption/legacy/fle2v2-Rangev2-Compact.yml

RUST-2024
There were three independent problems happening here:
* The serverless tests and serverless csfle tests were both trying to merge results into `results.xml`, and the second one would fail because the merge tool (appropriately) won't overwrite a file without an additional flag set.  Fixed this by changing the test script to do a rolling merge, which also has the nice effect that our tests don't need to include output file names or an explicit merge step any more.
* Many of the serverless tests were failing because `CRYPT_SHARED_LIB_PATH` wasn't being set; I tracked this down to a bug in the serverless setup scripts in drivers-evergreen-tools.  I've sent https://github.com/mongodb-labs/drivers-evergreen-tools/pull/491 for that and in the meanwhile pointed our testing at my branch …

RUST-2024 Fix serverless CSFLE tests

---

src/runtime.rs
src/runtime/join_handle.rs

The tracing instrumentation present in tokio (which feeds into
tokio-console) tracks the spawning location of each task. This can be
useful in understanding what each task is doing, especially if the tasks
aren't named (which is a `tokio_unstable` feature so not usually present
in published crates).
The location tracking isn't as useful when tasks are spawned from some
central location like the `mongodb` crate does, because all tasks have
the same spawn location. However, since the instrumentation uses the
`panic:Location` to determine the spawn location, the `#[track_caller]`
attribute macro can be used to ensure that the actual location is picked
up instead of the common one.
A side effect of using the `#[track_caller]` attribute is that the
single line output in the case of a panic …

track task spawn location for tokio instrumentation

---

src/change_stream/event.rs
src/test/change_stream.rs

Add more event fields: lsid, txnNumber and disambiguatedPaths

RUST-2030 Add more event fields: lsid, txnNumber and disambiguatedPaths

---

.evergreen/run-csfle-tests.sh

RUST-2040
[Passing run](https://spruce.mongodb.com/version/66eafe209e3d4a0007b6479d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
Apparently something changed in the drivers-evergreen-tools orchestration scripts that means the mongodb server binaries (which happens to include mongocryptd) are no longer in $PATH by default.

RUST-2040 Fix mongocryptd tests

---

.evergreen/env.sh

RUST-1968
[Passing run](https://spruce.mongodb.com/version/66f1af11a5704e0007658688/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
The new openssl installation on the Windows evergreen hosts has a _very_ nonstandard setup, both for dynamic and static linking; fortunately, the Rust openssl wrapper is quite flexible in how it can be built.  This sets it up to statically link to avoid having to futz around with `PATH`.

RUST-1968 Fix openssl test on windows

---

src/sdam/description/topology/server_selection/test/in_window.rs

RUST-2044
I was entirely unable to trigger the test failure (even running in a loop without my other updates), so either it's very low probability (< 0.1%) or needs some kind of external circumstances to occur.

RUST-2044 Improve server selection prose test

---

src/operation/bulk_write.rs
src/test/spec/json/crud/README.md
src/test/spec/json/crud/unified/aggregate-write-readPreference.json
src/test/spec/json/crud/unified/aggregate-write-readPreference.yml
src/test/spec/json/crud/unified/client-bulkWrite-partialResults.json
src/test/spec/json/crud/unified/client-bulkWrite-partialResults.yml
src/test/spec/json/crud/unified/db-aggregate-write-readPreference.json
src/test/spec/json/crud/unified/db-aggregate-write-readPreference.yml
src/test/spec/json/crud/unified/insertOne-dots_and_dollars.yml

`src/operation/bulk_write.rs` and `src/test/spec/json/crud/unified/client-bulkWrite-partialResults.[json|yml]` are the only relevant changes here; the rest got pulled in via a CRUD spec test sync

RUST-2037 Fix logic for populating bulk write partial result

---

src/client/options.rs
src/srv.rs
src/test/spec/initial_dns_seedlist_discovery.rs

RUST-2001
The actual changed logic is in `LookupHosts::validate` (which used to be in `SrvResolver::get_srv_hosts`), and is the conditional bit near the top checking the length of `original_hostname_parts`.  The rest of this is refactoring to make the new logic testable.

RUST-2001 Allow SRV hostnames with less than three parts

---

.evergreen/config.yml
.evergreen/with-secrets.sh

RUST-2049
Passing runs for [search index helpers](https://spruce.mongodb.com/version/66fec5fd6481480007581911/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) and [AWS Lambda](https://spruce.mongodb.com/version/66fed0f033b96200077e1751/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
Both of these just had stale credentials that weren't using the secrets manager; I updated them and introduced a helper script that makes it easier to run tests using managed credentials.

RUST-2049 Fix search index helpers and AWS Lambda tests

---

.evergreen/azure-kms-test/src/main.rs

RUST-2050
[Passing run](https://spruce.mongodb.com/version/6703ed3c99f9f30007997628/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
We just hadn't updated this for the recent API changes here.

RUST-2050 Fix Azure KMS test binary

---

.evergreen/run-driver-benchmark-unresponsive.sh
benchmarks/src/main.rs

RUST-2010
This disables the gridfs multi upload benchmark for now ([passing run](https://spruce.mongodb.com/version/6707e544bb7df200076311b8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)); I'll be filing an evergreen bug to follow up.
I've verified that it's specifically that benchmark - running that one alone is enough to trigger the "system unresponsive" status, and disabling it causes the suite to complete successfully.  Running the suite manually on a host with the same distro as the evergreen run works fine and the host remains responsive throughout, so there's definitely some weird interaction happening with the evergreen agent heartbeat.  Unfortunately, I could find very little documentation on how that works :(

RUST-2010 Work around evergreen agent bug(?)

---

src/index.rs
src/test/index_management.rs

RUST-2054
We didn't catch this before because the other tests checking index names all have integer values.

RUST-2054 Fix quoting when constructing index names

---

src/cmap/establish.rs
src/cmap/establish/handshake.rs
src/test/spec/faas.rs

This is preliminary to RUST-2000, which will need this kind of observability.  (And we probably should have been doing it from the start anyway.)

minor: refactor faas tests to validate metadata

---

src/test/spec/json/client-side-encryption/legacy/fle2v2-Rangev2-Compact.json
src/test/spec/json/client-side-encryption/legacy/fle2v2-Rangev2-Compact.yml
src/test/spec/json/crud/unified/client-bulkWrite-replaceOne-sort.json
src/test/spec/json/crud/unified/client-bulkWrite-replaceOne-sort.yml
src/test/spec/json/crud/unified/client-bulkWrite-updateOne-sort.json
src/test/spec/json/crud/unified/client-bulkWrite-updateOne-sort.yml
src/test/spec/json/transactions-convenient-api/unified/commit-retry.json
src/test/spec/json/transactions-convenient-api/unified/commit-retry.yml
src/test/spec/json/transactions-convenient-api/unified/commit-writeconcernerror.json
src/test/spec/json/transactions-convenient-api/unified/commit-writeconcernerror.yml
src/test/spec/json/transactions/unified/retryable-commit.json
src/test/spec/json/transactions/unified/retryable-commit.yml

Sync spec tests. Resolves RUST-2042 and RUST-2076.
Fixes the `test-serverless` task: [patch build](https://spruce.mongodb.com/version/672297118bfe2800075e0309).

RUST-2042 and RUST-2076 sync tests to fix serverless task

---

src/test/spec/json/uri-options/read-preference-options.json
src/test/spec/json/uri-options/read-preference-options.yml

RUST-2073
This also picked up the change for DRIVERS-989, which for whatever reason didn't spawn a RUST ticket.

RUST-2073 Sync tests for mixed case read preference tags

---

.config/nextest.toml
.evergreen/config.yml
.evergreen/find-python3.sh
.evergreen/happy-eyeballs-client.py
.evergreen/happy-eyeballs-server.py
.evergreen/run-happy-eyeballs-tests.sh
src/runtime/stream.rs
src/test.rs
src/test/happy_eyeballs.rs

DRIVERS-2949
With happy eyeballs on its way to being a driver spec, it needs a way for the behavior to be tested.  This PR implements a (relatively) simple python server that provides pairs of IPv4 and IPv6 ports on demand, with one of the pair being slow to start accepting incoming connections, and the corresponding Rust driver test using that server.
Originally I was hoping to have a static set of ports exposed by the test server (slow v4, fast v4, slow v6, fast v6), but it turns out that once you start accepting connections there's no way to delay the TCP handshake.  Instead, each test gets its own ephemeral pair of ports and the delay happens between binding to the port and accepting connections.
This also demonstrates the use of cargo nextest's `default-filter` to prevent these tests …

DRIVERS-2949 Test happy eyeballs behavior

---

src/client/auth.rs

Though there is pending work for OIDC (see RUST-1497), I expect this note is outdated.
The [3.0.0 release notes](https://github.com/mongodb/mongo-rust-driver/releases/tag/v3.0.0) document support for OIDC.
Change was motivated by [this slack thread](https://mongodb.slack.com/archives/CP893U9MX/p1730981781044979).

remove "not supported" note for `MongoDbOidc`

---

.evergreen/config.yml

DRIVERS-2949
This is well into the murky realm of unspecified and undocumented OS-specific behavior here.
As far as I can tell from experimentation, MacOS will let a port sit in the `bound`-but-not-`listen`ing limbo state that the test relies on and let TCP handshakes queue up to the normal TCP handshake timeout (~30s), Windows will only maintain a port in that state for a very short window (~1s) before treating it the same as Linux does (deny by default until `listen` is called).
That short window meant that the test on Windows would pass with ~70% success rate, which can be dialed up or down based on how much of a delay the test server used, but never enough to avoid normal delays from external variation making the test flaky.  Because of that, I've disabled the test on Windows.
If this …

DRIVERS-2949 Disable flaky Windows happy eyeballs test

---

Cargo.toml
deny.toml
macros/Cargo.toml
macros/src/lib.rs
src/action/find.rs
src/coll/options.rs

RUST-2103
There's enough machinery here that I thought it would be better to do it across multiple PRs - this one has the core added functionality and a single action converted to use it.  I'll follow up with PRs implementing conversions for the rest of the actions and the (hopefully minor) functionality updates those will likely need.
This is what the rustdocs for `find` look like with these changes ([old](https://docs.rs/mongodb/latest/mongodb/struct.Collection.html#method.find) for comparison):
And the new rustdocs for the setters ([old](https://docs.rs/mongodb/latest/mongodb/action/struct.Find.html#method.max_await_time)):

RUST-2103 Preliminary improvement for action rustdocs: `find`

---

src/test/spec/json/transactions-convenient-api/unified/commit-retry.json
src/test/spec/json/transactions-convenient-api/unified/commit-retry.yml
src/test/spec/json/transactions-convenient-api/unified/commit-writeconcernerror.json
src/test/spec/json/transactions-convenient-api/unified/commit-writeconcernerror.yml
src/test/spec/json/transactions/unified/retryable-commit.json
src/test/spec/json/transactions/unified/retryable-commit.yml

Follow-up to https://github.com/mongodb/mongo-rust-driver/pull/1236. Sync spec tests from https://github.com/mongodb/specifications/commit/da04aff83cf4fb01d0fe9b811a513cd030137c19.
Verified with [this patch](https://spruce.mongodb.com/version/673e45c6b58c46000702bc03) of the `test-serverless` task. The patch is based on an older commit: 3bf5e977949f570c0af192a2b81a091603148d8f. `test-serverless` is failing on `main` from seemingly unrelated tests. Those failures are not addressed in this PR.

RUST-2099 sync spec tests

---

benchmarks/README.md
src/change_stream.rs
src/client/csfle/options.rs
src/event/sdam.rs
src/event/sdam/topology_description.rs
src/sdam/description/server.rs
src/sdam/public.rs
src/sdam/srv_polling/test.rs
src/sync/change_stream.rs

Updates spec links to point to readthedocs or markdown files. I didn't bother with links in `src/test/spec/json` as I assume we'll pull in updated links there as we sync the tests.

RUST-2048 Update specification links

---

.evergreen/run-tests.sh
Cargo.toml
src/client/options.rs
src/client/options/test.rs
src/runtime.rs
src/runtime/pem.rs
src/runtime/tls_openssl.rs
src/runtime/tls_rustls.rs

RUST-226
This cherrypicks #1256 from mainline; I've tested this via Kevin's handy [integration test](https://github.com/kevinAlbs/rust-bootstrap/tree/ce1e7d02ca7cf0b897ee9d3f1cb42ac9364bdde9/test-tlsCertificateKeyFilePassword).

RUST-226 Support tlsCertificateKeyFilePassword (#1256)

---

src/action/bulk_write.rs

adds some missing closing brackets that I noticed when reviewing #1261

minor: fix `bulk_write` doc typo

---

macros/src/lib.rs
src/action/aggregate.rs
src/action/bulk_write.rs
src/action/client_options.rs
src/action/count.rs
src/action/create_collection.rs
src/action/find.rs
src/client/options/bulk_write.rs
src/coll/options.rs
src/db/options.rs

RUST-2103
This updates more actions to use the doc generation macros for option setters.  Some of these (notably `aggregate`) have setters split across multiple `impl` blocks with different type constraints that we want to show as a merged list in the documentation, so this required some changes to the machinery.
In particular, `option_setters_2` now accepts the name to export tokens for doc use under, and an optional list of extra setter names to include in those exported tokens.  This could be done at least two other ways:
* the extra names could be passed in to the `options_doc` macro; I didn't go with that because that would mean repeating them for each use of the macro, which is always at least twice (async/sync) and sometimes more if an action type is shared.
* the impls could be …

RUST-2103 Better documentation for action options, batch 2

---

src/bson_util.rs

Ok, this version only fixes the bug. I pushed the fuzzer as a branch to origin called `header_fuzz`

Fix read_document_bytes unchecked conversion bug

---

src/action/csfle/encrypt.rs
src/client/csfle/client_encryption/encrypt.rs
src/options.rs
src/test/csfle.rs

Addresses the bug described in [this comment](https://github.com/mongodb/mongo-rust-driver/pull/1272#discussion_r1900275603)

Disallow setting `query_type` for `encrypt_expression`

---

src/client/csfle/client_encryption.rs

`EncryptedClientBuilder` isn't currently part of the public API, which means its docs aren't loaded on our documentation page (see lack of link on the return type [here](https://docs.rs/mongodb/latest/mongodb/struct.Client.html#method.encrypted_builder)). This exports it in the `client_encryption` module to make the docs visible.

Make `EncryptedClientBuilder` publicly accessible

---

src/cmap/conn.rs
src/test/csfle.rs

The certs used in `kms_retry` are not valid for connecting with serverless

Skip KMS retry test on serverless

---

src/action/insert_many.rs
src/results.rs

RUST-1891
Implements `Default` on the types contained in the `results` module. I don't think there's anything of value to test here.

RUST-1891 Implement `Default` on results structs

---

src/runtime/tls_openssl.rs
src/srv.rs

Fixes #1291. I've tested this locally, but I also filed RUST-2143 to test all feature flag combinations in CI so that we can catch these kinds of errors.

Fix compilation when `dns-resolver` is disabled

---

src/runtime/tls_openssl.rs

RUST-2144 Use recommended openssl probing API

---

.evergreen/release-manual-trigger.sh

RUST-2136
This adds a script to manually poke the evergreen release workflow.  If it seems reasonable to you, I'll add this to the release checklist as a fallback for if the automation fails.

RUST-2136 Add manual release trigger script

---

src/runtime/tls_openssl.rs

HELP-70689
I left the old lines present but commented out just as a reference.  Once this is merged, I'll cherrypick it to the `ipv6-backport` branch.

HELP-70689 Use openssl cert parsing when openssl-tls is enabled

---

src/client.rs

RUST-2155
I did try to have this use the same set of `pending_drops` that other cleanup tasks do, but that led to some _really_ loopy, deadlock-prone, hard-to-reason-about logic with `Client::shutdown` waiting on its own drop...

RUST-2155 Precreate cleanup task for endSessions

---

src/test/spec/json/load-balancers/non-lb-connection-establishment.json
src/test/spec/json/load-balancers/non-lb-connection-establishment.yml

Sync `non-lb-connection-establishment` test to https://github.com/mongodb/specifications/commit/d05c33e0a6124ee7d1a9de665084d540b2ff06c5
This is intended to proactively avoid tests failure once drivers start testing 8.1 builds. See DRIVERS-3108.

RUST-2160 sync `non-lb-connection-establishment` test

---

.evergreen/config.yml
src/test/spec/sessions/sessions_not_supported.rs

Running `buildInfo` on `mongocryptd` 8.1+ causes errors (perhaps related to [SERVER-87874](https://jira.mongodb.org/browse/SERVER-87874)?) for the sessions-not-supported tests. I skipped the tests on 8.1+ for now, but we should do RUST-1447 so that we don't need to call `buildInfo` and other metadata-retrieving commands for each test client we create.

minor: skip sessions not supported tests on 8.1+

---

src/client/options.rs
src/sdam/description/server.rs
src/sdam/test.rs

HELP-68823
This wasn't the fix that I was intending to put into mainline, but that turns out to have a lot more in the way of wrinkles than I expected.  In particular, we have some public APIs (e.g. [`ToplogyDescription::servers`](https://docs.rs/mongodb/latest/mongodb/event/sdam/struct.TopologyDescription.html#method.servers)) that hand out `&ServerDescription` values, which locks us into having the underlying data structure storing that type either as the primary (how it's currently done) or as some kind of internally-mutable cache (ew).
There may be some clever path forward for split types that maintains API compatibility that I didn't see, but for the moment I think it's best to get the simple fix in and unblock downstream users.  This PR, while minimal, fixes the core issue and …

HELP-68823 Fix invalid_me comparison and normalize host strings

---

.evergreen/MSRV-Cargo.toml.diff

RUST-2165
The original dependency that necessitated the ticket yanked its version, but a couple others showed up since then.

RUST-2165 Pin transitive deps for MSRV

---

src/client.rs

RUST-2155 Precreate cleanup task for endSessions (#1305)

---

README.md

RUST-1375
This:
* gets rid of the "will rarely be increased" phrase; we tried to hew to this by jumping through hoops to do it as little as possible but literally no other crates I could find make this promise.   Likewise "if it ever is" was long since dead verbiage 🙂.
* Sets the six month rolling window.  Of those crates that do provide a written policy, this seems to be a little on the conservative side of normal; only `rustls` sets a longer window and most do a shorter one.
I considered defining the window in terms of a set number of releases instead of a time period (both are common in the crate ecosystem) and went with time period because I find that a little easier to personally reason about.

RUST-1375 Update MSRV policy

---

Cargo.toml
src/runtime/tls_rustls.rs

rustls 0.21 is EOL for security support at the end of March 2025.
- Drop rustls-pemfile, as it is now incorporated into rustls-pki-types; use the new iterator-based API.
- Use the ring-based provider, to align with previous version's build-time requirements.

RUST-2171 Update `rustls` to 0.23

---

src/test/spec/json/server-discovery-and-monitoring/rs/secondary_ipv6_literal.json
src/test/spec/json/server-discovery-and-monitoring/rs/secondary_ipv6_literal.yml

Verified with this [patch build](https://spruce.mongodb.com/version/67cb381fab4bc8000769cd72/). The test is independent of the live server topology since it uses mock data.

RUST-2175 add IPv6 literal test

---

src/test/spec/oidc.rs

RUST-2020
The driver behavior was already correct, so this entailed adding a new prose test (4.4). Note that the assertions on `saslStart` events for this test will not run properly until RUST-2176 is implemented. I also added a few other reauth tests we were missing (4.2, 4.3).

RUST-2020 Ignore speculative authentication on reauthentication

---

src/sdam/description/topology/server_selection.rs

RUST-2179 Ignore whether nodes are data-bearing when `directConnection` is true

---

Cargo.toml
README.md
macros/Cargo.toml
src/lib.rs

My plan is to merge this into main first and then pick this commit and the bug fix onto 3.2.x so that we don't have to update the version numbers on main after the release.

RUST 2180 Update version numbers for 3.2.3

---

src/test/spec/json/load-balancers/non-lb-connection-establishment.json
src/test/spec/json/load-balancers/non-lb-connection-establishment.yml

Reverts commit f09370980410e86e6f25c6a1c2471f1c3d86187a.
[SERVER-101078](https://jira.mongodb.org/browse/SERVER-101078) is fixed on 8.1.0-rc0 and enables running this test again.

RUST-2168 Revert skip to `non-lb-connection-establishment`

---

.evergreen/install-dependencies.sh
.evergreen/unsymlink.py

RUST-2181
This works around the cygwin symlink bug (https://github.com/rust-lang/rustup/issues/4239) with a small script that replaces the symlinks with actual copies.  This wouldn't be a good workaround for a long-lived installation because it'd mess with the rustup upgrade process, but because we're doing a clean install every time and then discarding it once tests are done it's fine here.
I went with python for the script rather than bash because I think it ends up being substantially more readable.

RUST-2181 Fix rustup installation on windows

---

src/sdam/monitor.rs
src/test/spec/sessions.rs

RUST-2005
It turns out that we were accidentally doing half of this already - because monitoring heartbeats don't use the executor layer, they don't gossip cluster time to the server.  Unfortunately, that also means we can't assert in test code that the commands sent don't contain `$clusterTime` because it's not captured by normal event machinery.
This PR adds the suppression of cluster times coming from the server on monitoring hellos and the new prose test described.

RUST-2005 Test that heartbeats don't gossip cluster time

---

.evergreen/config.yml

RUST-2172
Happily, no changes were needed.  Full test against older versions is [here](https://spruce.mongodb.com/version/67dc3757e942f7000766eea2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) - I left those evergreen configs present but commented out to make it easy to re-run in the future if needed.

RUST-2172 Test on Graviton processor

---

src/test/spec/json/unified-test-format/invalid/clientEncryptionOpts-kmsProviders-invalidName.json
src/test/spec/json/unified-test-format/invalid/clientEncryptionOpts-kmsProviders-invalidName.yml
src/test/spec/json/unified-test-format/invalid/expectedCommandEvent-commandFailedEvent-databaseName-type.json
src/test/spec/json/unified-test-format/invalid/expectedCommandEvent-commandFailedEvent-databaseName-type.yml
src/test/spec/json/unified-test-format/invalid/expectedCommandEvent-commandSucceededEvent-databaseName-type.json
src/test/spec/json/unified-test-format/invalid/expectedCommandEvent-commandSucceededEvent-databaseName-type.yml
src/test/spec/json/unified-test-format/invalid/expectedLogMessagesForClient-ignoreExtraMessages-type.json
src/test/spec/json/unified-test-format/invalid/expectedLogMessagesForClient-ignoreExtraMessages-type.yml
src/test/spec/json/unified-test-format/invalid/expectedLogMessagesForClient-ignoreMessages-items.json
src/test/spec/json/unified-test-format/invalid/expectedLogMessagesForClient-ignoreMessages-items.yml
src/test/spec/json/unified-test-format/invalid/expectedLogMessagesForClient-ignoreMessages-type.json
src/test/spec/json/unified-test-format/invalid/expectedLogMessagesForClient-ignoreMessages-type.yml
src/test/spec/json/unified-test-format/invalid/expectedSdamEvent-topologyDescriptionChangedEvent-additionalProperties.json
src/test/spec/json/unified-test-format/invalid/expectedSdamEvent-topologyDescriptionChangedEvent-additionalProperties.yml
src/test/spec/json/unified-test-format/invalid/runOnRequirement-authMechanism-type.json
src/test/spec/json/unified-test-format/invalid/runOnRequirement-authMechanism-type.yml
src/test/spec/json/unified-test-format/valid-fail/entity-findCursor-malformed.yml
src/test/spec/json/unified-test-format/valid-fail/ignoreResultAndError-malformed.yml
src/test/spec/json/unified-test-format/valid-fail/operator-matchAsDocument.json
src/test/spec/json/unified-test-format/valid-fail/operator-matchAsDocument.yml
src/test/spec/json/unified-test-format/valid-fail/operator-matchAsRoot.json
src/test/spec/json/unified-test-format/valid-fail/operator-matchAsRoot.yml

This in tandem with #1342 resolves RUST-2075. The rest of the synced files are tests we missed when implementing larger pieces of work that added new unified test runner functionality.

Sync `valid-fail` and `invalid` unified format tests

---

src/operation/find.rs
src/test/spec/crud.rs
src/test/spec/json/crud/unified/bypassDocumentValidation.json
src/test/spec/json/crud/unified/bypassDocumentValidation.yml
src/test/spec/json/crud/unified/estimatedDocumentCount.json
src/test/spec/json/crud/unified/estimatedDocumentCount.yml
src/test/spec/json/crud/unified/find.json
src/test/spec/json/crud/unified/find.yml
src/test/spec/json/crud/unified/findOne.json
src/test/spec/json/crud/unified/findOne.yml

Code changes are for RUST-2071. Also pulls in syncs for:
- RUST-2088
- RUST-2082
- RUST-2070

RUST-2071 Increase batchSize for find when batchSize == limit

---

src/sdam/description/topology.rs
src/test/spec/json/server-discovery-and-monitoring/README.md
src/test/spec/json/server-discovery-and-monitoring/rs/new_primary.json
src/test/spec/json/server-discovery-and-monitoring/rs/new_primary.yml
src/test/spec/json/server-discovery-and-monitoring/rs/new_primary_new_electionid.json
src/test/spec/json/server-discovery-and-monitoring/rs/new_primary_new_electionid.yml
src/test/spec/json/server-discovery-and-monitoring/rs/new_primary_new_setversion.json
src/test/spec/json/server-discovery-and-monitoring/rs/new_primary_new_setversion.yml
src/test/spec/json/server-discovery-and-monitoring/rs/primary_disconnect_electionid.json
src/test/spec/json/server-discovery-and-monitoring/rs/primary_disconnect_electionid.yml
src/test/spec/json/server-discovery-and-monitoring/rs/primary_disconnect_setversion.json
src/test/spec/json/server-discovery-and-monitoring/rs/primary_disconnect_setversion.yml
src/test/spec/json/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.json
src/test/spec/json/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.yml
src/test/spec/json/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.json
src/test/spec/json/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.yml
src/test/spec/json/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.json
src/test/spec/json/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.yml
src/test/spec/json/server-discovery-and-monitoring/rs/use_setversion_without_electionid.json
src/test/spec/json/server-discovery-and-monitoring/rs/use_setversion_without_electionid.yml

RUST-2095
We skip a lot of these tests because we haven't implemented RUST-1446 yet but enough run that I'm confident this is correct.

RUST-2095 Add an error message when marking primaries stale

---

src/action/aggregate.rs

RUST-2191
Forgot to carry the `T`.
I added a typelevel test to make sure this fixed it, and looked to see if we made this mistake elsewhere, but the only comparable action is `Watch` and that doesn't have this problem.

RUST-2191 Fix type propagation for Aggregate::session

---

src/action/gridfs.rs
src/action/gridfs/delete.rs
src/action/gridfs/rename.rs
src/test/spec/json/gridfs/delete.json
src/test/spec/json/gridfs/delete.yml
src/test/spec/json/gridfs/deleteByName.json
src/test/spec/json/gridfs/deleteByName.yml
src/test/spec/json/gridfs/download.json
src/test/spec/json/gridfs/download.yml
src/test/spec/json/gridfs/downloadByName.json
src/test/spec/json/gridfs/downloadByName.yml
src/test/spec/json/gridfs/renameByName.json
src/test/spec/json/gridfs/renameByName.yml
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/operation/gridfs.rs

RUST-2090
This adds the helpers for RUST-2090 and RUST-2091; it also syncs _some_ of the changes from RUST-2080 but there are wrinkles with the added tests for gridfs rename (see comments in DRIVERS-3023) so those aren't in here.  With the exception of the `rename.yaml`/`.json` that adds, this brings the `gridfs` test path fully up to sync.

RUST-2090/gridfs helpers

---

.github/CODEOWNERS

To meet requirement of DRIVERS-3098. Follows pattern from other drivers: [PHP](https://github.com/mongodb/mongo-php-library/blob/a4ccccd9011bad978e6f0d52efd1a512ef64d35a/.github/CODEOWNERS), [C#](https://github.com/mongodb/mongo-csharp-driver/blob/main/CODEOWNERS).

RUST-2195 add CODEOWNERS

---

src/client/executor.rs
src/client/session.rs
src/operation/bulk_write.rs
src/test/bulk_write.rs

RUST-2131 Fix bulk write cursor iteration on load balanced topologies

---

src/action/run_command.rs
src/client/csfle/state_machine.rs
src/coll.rs
src/operation/run_command.rs
src/test/db.rs

The database `run_command` api only takes a Document, while internally it is later converted to a RawDocumentBuf before execution. In a situation where you already have the command as a RawDocumentBuf in the first place, an unneeded conversion RawDocumentBuf -> Document -> RawDocumentBuf is required to use this API.
I noticed that there was this `RunCommand::new_raw` method, which was feature gated behind "in-use-encryption". I'm not sure the reason for this gate, but it's trivial to remove it and use it with the additional `database.raw_run_command` method added here.
I only added `raw_run_command`, but a similar `raw_run_cursor_command` could also be added which takes RawDocumentBuf as well.

RUST-2198 Add `run_raw_command` method

---

src/operation/bulk_write.rs

#1356 branched before but was merged after #1358, so the change to the internal API for `RunCommand` wasn't applied to the killCursors call added in #1358.

Fix RunCommand construction for bulk write killCursors

---

.evergreen/config.yml

This will unblock PRs from merging when `cargo-deny` is failing.

RUST-1907 Move `cargo-deny` check to separate buildvariant

---

src/action/gridfs/rename.rs
src/test/spec/json/gridfs/rename.json
src/test/spec/json/gridfs/rename.yml
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/operation/collection.rs
src/test/spec/unified_runner/operation/gridfs.rs
src/test/spec/unified_runner/operation/rename.rs

RUST-2080
This syncs the tests and adds the missing file-not-found logic that the tests caught.
This did require making the `rename` test operation a little odd because it can either target a collection, in which case it accepts arguments of the form `{ to: String }`, or it can target a gridfs bucket, where the arguments are `{ id: Bson, newFilename: String }`.  We parse the test file json into `TestOperation` values at file load time, where entity type isn't known, so we can't have distinct operation types for "rename collection" and "rename bucket", so instead there's now a wrapper layer that defers parsing the args document until the test is actually executed at which point it checks entity type and parses appropriately.

RUST-2080 spec tests (and fix) for gridfs rename

---

src/cmap/conn.rs
src/cmap/conn/wire/message.rs

RUST-2204
It turns out that we were only enforcing `maxMessageSizeBytes` for messages we receive, not for ones we send; this adds it for outgoing as well.

RUST-2204 Enforce size limits on outgoing messages

---

src/test/bulk_write.rs

changes for https://github.com/mongodb/specifications/pull/1785

RUST-2209 Assert `InvalidArgument` errors are returned for too-large bulk write inputs

---

.evergreen/check-clippy.sh
Cargo.lock
Cargo.toml
src/client/session/action.rs
src/test/documentation_examples.rs
src/test/spec/transactions.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/operation/transaction.rs
src/test/spec/v2_runner/operation.rs

RUST-2166
This adds the slightly-awkwardly-named-but-much-easier-to-use `and_run2` method, and updates almost all* of the callers to use the new method.  It also pulls out the method body into a macro so rather than being duplicated across the async and sync (and now new-async) implementations it's shared across all three.
\* A couple of test operations ran into a rustc bug that mean they don't compile with the new method due to really fun `implementation of 'std::marker::Send' is not general enough` errors, so I left those with the old method.  I think it pretty unlikely actual library users will run into this (the trigger condition here is the transaction closure capturing a value that has a manual `Send` impl when `and_run2` is being called inside multiple layers of `.box()`ed futures …

RUST-2166 Update convenient transactions API to use async closures

---

.github/dependabot.yml

Here's an example PR from my fork: https://github.com/isabelatkinson/mongo-rust-driver/pull/5, and a patch for those changes: https://spruce.mongodb.com/version/682bbb5f2a3ef700075f76b4/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Ecompile%24.
This does the equivalent of running `cargo update`; i.e., it doesn't update the dependencies in `Cargo.toml`, as doing so may bump to a new major version requiring code changes and/or an MSRV update. Dependabot does allow configuring minor version bumps only, but this breaks for pre-1.0 dependencies, for which a minor version update (e.g. 0.2.0->0.3.0) can include breaking changes.
I chose a weekly cadence as I expect we should be able to merge these PRs as-is most of the time, but we can revisit if it becomes disruptive.

RUST-577 Bump dependencies with dependabot

---

.evergreen/config.yml

RUST-2224
This adds the explicit `ec2.assume_role` so we're not using the (now-removed) implicit instance credentials.  Note that the tests are still flaky so they can still fail occasionally, but that predates this breakage; this is fixing the "SYSTEM FAILED" status.

RUST-2224 Fix OIDC test role setup

---

Cargo.lock
src/bson_compat.rs
src/bson_util.rs
src/cmap/establish/handshake.rs
src/lib.rs
src/operation/update.rs
src/sdam/description/server.rs

RUST-1887
When I went to update the driver for the lossy utf8 changes, I realized I hadn't been updating for the previous changes, and it'll be much easier to review as distinct PRs, so here's the first one.  Very little compatibility machinery needed so far to make it work with both 2.x and 3.0.

RUST-1887 Update driver for bson append changes

---

.evergreen/compile-only.sh

The MSRV task generates a fresh lockfile, which pulls in the latest commit on the bson-rust main branch for the `bson-3` dependency, which will break compilation if we haven't yet updated the driver to accommodate any recent breaking changes. This PR updates the MSRV check not to compile with `bson-3` enabled so that merging PRs isn't blocked on us making the necessary changes in the driver when the bson API breaks. (I'm not concerned about losing coverage because we already test MSRV compilation for the bson crate, so we know a 1.81-compliant version exists.) If this approach sounds good, I'll file a ticket to revert these changes once the 3.0 API is stabilized and integrated into the driver.

Fix MSRV check

---

src/client/options.rs
src/client/options/bulk_write.rs
src/coll/options.rs
src/db/options.rs
src/operation.rs
src/operation/aggregate.rs
src/operation/commit_transaction.rs
src/operation/create.rs
src/operation/create_indexes.rs
src/operation/delete.rs
src/operation/drop_collection.rs
src/operation/drop_database.rs
src/operation/drop_indexes.rs
src/operation/find_and_modify.rs
src/operation/find_and_modify/options.rs

Replaced `remove_empty_write_concern` macro with serde attribute `#[serde(skip_serializing_if = "write_concern_is_empty")]` to remove empty write concerns before serialization. 
Applied the new serde attribute to `write_concern` fields in the following structs that previously used `remove_empty_write_concern`:
- `TransactionOptions` 
- `DeleteOptions` 
- `AggregateOptions` 
- `CreateIndexOptions` 
- `DropCollectionOptions` 
- `CreateCollectionOptions` 
- `DropDatabaseOptions` 
- `FindAndModifyOptions` 
- `DropIndexOptions` 
Also updated additional structs with `write_concern` fields that serialized empty values before:
- `BulkWriteOptions`
- `InsertOneOptions`
- `ReplaceOptions`
- `FindOneAndDeleteOptions`
- `FindOneAndReplaceOptions`
- `FindOneAndUpdateOptions`
Special cases 
Certains …

RUST-1826 Use serde attribute to remove empty write concerns

---

Cargo.lock
Cargo.toml

Replaces the deprecated `sha-1` crate with `sha1` as described in their README. 
See #1382.

[RUST-2227] Migrate to sha1 crate

---

Cargo.lock

Bumps the `bson-3` dependency to the latest commit. There weren't any driver changes needed to accommodate https://github.com/mongodb/bson-rust/pull/555, so this PR is just for the sake of getting us up-to-date.

minor: bump `bson-3` dependency

---

Cargo.lock
Cargo.toml
src/cmap/conn.rs
src/cmap/conn/wire/message.rs

RUST-2233
This picks up RUST-2204 (which fixes RUST-2234) and RUST-2227.  After this the branch should be ready for release.

RUST-2233 Cherrypick more fixes for 3.2.4 release

---

Cargo.lock
src/bson_compat.rs
src/error.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/v2_runner/operation.rs

RUST-1406
I decided to provide a single unified `ErrorKind::Bson` variant when the user's opted in to `bson-3` rather than having a run-time switch to emulate the old behavior.

RUST-1406 Update driver to use merged bson serde errors

---

Cargo.lock
Cargo.toml

Enables `serde_json-1` for testing and when `tracing-unstable` is enabled.

RUST-2240 Enable bson `serde_json-1` feature flag where necessary

---

Cargo.lock
src/coll/options.rs
src/concern.rs
src/gridfs.rs
src/index/options.rs
src/results.rs
src/serde_util.rs

We were only using two of the helper functions, so I added them to the driver's `serde_util` module rather than adding conditional logic for helper functions vs. `serde_with` in `bson_compat`.

RUST-1748 Fix use of functions from `bson::serde_helpers`

---

README.md

- Add Axum-MongoDB CRUD API example reference to Axum [repository](https://github.com/tokio-rs/axum).
- Format README file.
- Add empty lines before/after headings (if required).
- Fix table layout.

README: add reference for axum example

---

src/action/client_options.rs
src/client/options.rs
src/client/options/test.rs

Fixes handling of the `tlsInsecure` option in a URI. `tlsInsecure=bool` now sets `TlsOptions::allow_invalid_certificates` and `TlsOptions::allow_invalid_hostnames` (if `openssl-tls` is enabled) to the value of `bool`.
Note that `tlsInsecure` can _only_ be set via a URI; the `ConnectionString` and `ClientOptions` types both store the `TlsOptions` type, which only has fields for the more granular options.

RUST-2264 Fix handling of tlsInsecure in the URI

---

Cargo.toml
etc/update_version/src/main.rs
src/lib.rs

RUST-2142
This updates the `update_version` helper to work with the bson2/bson3 setup and disables the WIP `atlas_search` module from release.

RUST-2142 Pre-3.0 release tooling update

---

src/test/spec/json/auth/mongodb-oidc.md
src/test/spec/oidc.rs

[link](https://github.com/mongodb/specifications/blob/master/source/auth/tests/mongodb-oidc.md#45-reauthentication-succeeds-when-a-session-is-involved)

RUST-2226 Add a prose test for OIDC reauthentication when a session is involved

---

src/cursor.rs
src/sync/cursor.rs
src/test/cursor.rs

Resolves #1258
- Made `has_next()` pub + added doc comments
- Added `has_next()` to sync cursor API
- Added simple test

RUST-2113 Add has_next to cursor API

---

src/action/gridfs/download.rs
src/bson_util.rs
src/client/options.rs
src/cmap/conn/stream_description.rs
src/cmap/options.rs
src/hello.rs
src/index/options.rs
src/lib.rs
src/sdam/description/server.rs
src/sdam/description/topology/server_selection/test/in_window.rs
src/sdam/description/topology/test.rs
src/sdam/description/topology/test/sdam.rs
src/test/bulk_write.rs
src/test/coll.rs

RUST-2127
This enables the `clippy::cast_sign_loss` lint and fixes all the locations it flagged.  These fell into four fuzzy categories:
* surrounding checks ensure it's infallible, but the Rust compiler can't prove it: these are now `try_into().unwrap()` so if the checks miss something it'll cause a panic rather than silent misbehavior;
* conversion between float and integer: there's now an explicit function for that (that just calls lint-disabled `as`) to make it clear that's what's intended;
* assuming a technically-signed value from the server is always actually unsigned: this is now checked at parse time and handled as an unsigned value everywhere beyond that;
* test assertions, which now also use `try_into().unwrap()`

RUST-2127 lint for sign loss when casting

---

.evergreen/run-csfle-tests.sh
Cargo.lock
Cargo.toml
README.md
src/action/csfle/encrypt.rs
src/client/csfle/client_encryption.rs
src/client/csfle/client_encryption/encrypt.rs
src/test.rs
src/test/csfle/prose.rs
src/test/spec/json/testdata/client-side-encryption/data/encryptedFields-prefix-suffix.json
src/test/spec/json/testdata/client-side-encryption/data/encryptedFields-substring.json
src/test/spec/unified_runner/test_file.rs

RUST-2237
I added an unstable feature flag for this in case the API changes when texts indexes are GA.

RUST-2237 Support for text indexes in explicit encryption
