src/cmap/test/mod.rs

[RUST-304](https://jira.mongodb.org/browse/RUST-304)
This PR is a potential fix for the failures identified in RUST-304. It adds a brief delay to the end of a CMAP spec test run. This delay should allow enough time for the background tasks spawned in the various `Drop` implementations to be scheduled and subsequently emit events before we check for the presence of those events. Prior to this, the tests were checking for the events immediately, which could occasionally happen before the tasks were scheduled.

RUST-304 Fix race condition in CMAP spec tests

---

Cargo.toml

Please see https://jira.mongodb.org/browse/RUST-306

RUST-306 Disable default features on pbkdf2 crate

---

Cargo.toml

Additionally I have disabled the default features to (slightly) speedup compilation.

Update the os_info crate version

---

src/db/options.rs
src/operation/create/test.rs

Renamed validation field to validator and added a test for the same

RUST-8 Create/modify collection helpers needs to support creating "validators"

---

src/operation/update/test.rs

This PR adds a test to make sure that hints get added to updates properly

RUST-376 Added test to verify if hints have been added to update properly

---

README.md

update document  dependence

---

src/client/auth/scram.rs
src/sdam/description/server.rs

This PR fixes clippy errors that surfaced after an update.

minor: fix clippy errors

---

src/change_stream/document.rs
src/change_stream/mod.rs
src/change_stream/options.rs
src/client/mod.rs
src/coll/mod.rs
src/db/mod.rs
src/lib.rs
src/options.rs

This PR is the layout of the API interface for changeStreams.

RUST-519 Implement public change streams API

---

src/lib.rs

This PR fixes a typo in compiler messages.

minor: fix typo

---

src/change_stream/mod.rs
src/change_stream/options.rs
src/client/mod.rs
src/client/options/mod.rs
src/coll/mod.rs
src/db/mod.rs
src/operation/mod.rs
src/operation/watch/mod.rs
src/operation/watch/test.rs
src/test/client.rs
src/test/coll.rs
src/test/db.rs

This PR implements the watch operation and the watch functions for client/coll/database

RUST-520 Implement 'watch' operation

---

src/client/auth/scram.rs

RUST-683 Use hashmap's entry api

---

src/client/options/mod.rs
src/test/documentation_examples.rs
src/test/mod.rs

RUST-649 Document versioned API usage with examples

---

src/client/options/mod.rs
src/cmap/establish/handshake/mod.rs
src/cmap/mod.rs
src/coll/options.rs
src/test/util/matchable.rs

minor: fix clippy for 1.52.0

---

src/bson_util/mod.rs
src/sdam/description/topology/server_selection/test/mod.rs

RUST-765
This updates a few places that were broken by recent breaking changes to the BSON library as part of RUST-765.

RUST-765 Update usages of BSON library

---

README.md
tests/readme_examples.rs

RUST-736
This PR makes some minor changes to the README to reflect the 2.0 API, mostly by focusing on serde interop.
rendered [here](https://github.com/patrickfreed/mongo-rust-driver/tree/RUST-736/readme#readme)

RUST-736 Update README examples to reflect usage of 2.0 API

---

src/cmap/conn/command.rs
src/coll/mod.rs
src/error.rs
src/operation/delete/test.rs
src/operation/insert/test.rs
src/operation/mod.rs
src/operation/update/test.rs
src/test/spec/retryable_writes/mod.rs
src/test/spec/v2_runner/mod.rs

RUST-830 Consolidate error label storage to `Error::labels`

---

src/cmap/conn/wire/header.rs
src/cmap/conn/wire/message.rs

RUST-840 Buffer all reads and writes to/from sockets

---

.evergreen/check-all.sh
README.md

Pretty straightforward! If we want to add any other tests to this we should probably add them manually here.
I also think it could be helpful to add this script into a pre-commit hook, but that's probably another discussion.

RUST-652 Add script to run all linter tests

---

.gitignore

Minor: Add `.DS_Store` to `.gitignore`

---

README.md
src/lib.rs

RUST-730
Once this is merged, I'll push the same policy to the BSON repo.

RUST-730 Add MSRV policy to documentation

---

src/test/spec/json/change-streams/README.rst
src/test/spec/json/change-streams/unified/change-streams-errors.json
src/test/spec/json/change-streams/unified/change-streams-errors.yml
src/test/spec/json/change-streams/unified/change-streams-resume-allowlist.json
src/test/spec/json/change-streams/unified/change-streams-resume-allowlist.yml
src/test/spec/json/change-streams/unified/change-streams-resume-errorLabels.json
src/test/spec/json/change-streams/unified/change-streams-resume-errorLabels.yml
src/test/spec/json/change-streams/unified/change-streams.json
src/test/spec/json/change-streams/unified/change-streams.yml
src/test/spec/json/unified-test-format/invalid/expectedEventsForClient-ignoreExtraEvents-type.json
src/test/spec/json/unified-test-format/invalid/expectedEventsForClient-ignoreExtraEvents-type.yml
src/test/spec/json/unified-test-format/valid-pass/expectedEventsForClient-ignoreExtraEvents.json
src/test/spec/json/unified-test-format/valid-pass/expectedEventsForClient-ignoreExtraEvents.yml
src/test/spec/unified_runner/mod.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_file.rs

RUST-767
This updates the Rust driver's version of the change stream tests to match them as they were merged into the spec repo, and makes the few minor tweaks to the runner needed to match.

RUST-767 Update change stream unified tests

---

src/test/client.rs

RUST-1078 Fix and start running test for clientMetadata in handshake

---

src/client/options/mod.rs

Splits the sync and async APIs each into two methods, one which accepts a resolver config and one which does not.

RUST-1193 follow-up: minor adjustment to ConnectionString -> ClientOptions API

---

Cargo.toml
src/bson_util/mod.rs
src/cmap/conn/mod.rs
src/cmap/test/event.rs
src/event/cmap.rs
src/event/command.rs
src/event/sdam/mod.rs
src/event/sdam/topology_description.rs
src/hello.rs
src/sdam/description/server.rs
src/sdam/description/topology/mod.rs
src/sdam/public.rs
src/test/atlas_planned_maintenance_testing/json_models.rs
src/test/atlas_planned_maintenance_testing/mod.rs
src/test/mod.rs
src/test/spec/mod.rs
src/test/spec/unified_runner/entity.rs
src/test/spec/unified_runner/mod.rs
src/test/spec/unified_runner/operation.rs
src/test/spec/unified_runner/test_file.rs
src/test/spec/unified_runner/test_runner.rs
src/test/util/event.rs

Workload executor specification: https://mongodb-labs.github.io/drivers-atlas-testing/spec-workload-executor.html
There are still a few kinks in the implementation that I'm working through in testing, but the bulk of the code should be ready for review.

RUST-645 / RUST-1245 Add Atlas planned maintenance testing workload executor

---

src/test/spec/transactions.rs
src/test/spec/versioned_api.rs

This PR removes some unnecessary tests that I found while poking around our test runner code during Skunkworks.

minor: remove unnecessary tests

---

src/test/spec/change_streams.rs
src/test/spec/json/change-streams/unified/change-streams-resume-errorLabels.json
src/test/spec/json/change-streams/unified/change-streams-resume-errorLabels.yml

RUST-1412 sync StaleShardVersion change streams test

---

src/test/spec/load_balancers.rs

RUST-1448 Unskip ChangeStream load balancer tests

---

src/test/atlas_planned_maintenance_testing/mod.rs

corresponding `drivers-atlas-testing` patch: https://spruce.mongodb.com/version/633452a2c9ec4431d3dde2f8/tasks?limit=100&page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Etests-rust__driver~rust-main_platform~ubuntu-18.04_runtime~rust-latest%24

RUST-1474 Fix JSON file construction in workload executor

---

.evergreen/config.yml

RUST-843 Bump evergreen macos hosts to 11.00

---

.evergreen/config.yml
.evergreen/run-csfle-tests.sh

RUST-1535
This updates evergreen configuration to run csfle tests against a serverless setup.

RUST-1535 Run csfle tests against serverless

---

src/sync/test.rs

RUST-845
This PR introduces the transaction retry logic demonstrated in #801 to the sync transaction test, which was encountering transient transaction errors and causing build failures. I think the failures are related to the collection drop and subsequent create that happens at the beginning of the test.

RUST-845 Properly retry transactions in sync transactions test

---

src/test/spec/command_monitoring/mod.rs
src/test/spec/json/command-logging-and-monitoring/README.rst
src/test/spec/json/command-logging-and-monitoring/monitoring/writeConcernError.json
src/test/spec/json/command-logging-and-monitoring/monitoring/writeConcernError.yml

RUST-1567
With RUST-1574 done, this is just a straight test sync.

RUST-1567 Sync CLAM write concern error test

---

src/client/options/mod.rs
src/event/cmap.rs

Updating the value shown in docs to reflect the change in #346

update default value in docs

---

src/cmap/establish/handshake/mod.rs

RUST-1501
The spec needed a few minor updates after this was submitted (order of precedence for truncation and vercel handling), this brings the Rust implementation up to match.

RUST-1501 Update faas metadata collection

---

src/coll/mod.rs

Force non-human readable serialization in collections

---

src/coll.rs

This PR was merged into the `2.6.x` branch; adding to main here as well.

Force non-human readable serialization in collections (#919)

---

src/client.rs
src/id_set.rs

RUST-1779 Fix a memory leak in cleanup tracking (#979)

---

.evergreen/check-clippy.sh

RUST-1920
Right now this report goes nowhere; it will eventually be uploaded to S3 for ingestion by Silk, but that feature's not ready yet.

RUST-1920 Generate a SARIF report from clippy

---

src/action/bulk_write.rs
src/client/options/bulk_write.rs
src/error/bulk_write.rs
src/results/bulk_write.rs

RUST-1851 / RUST-1852 Bulk write sync API and documentation

---

src/client/auth.rs

Went through the spec again, this was all that was missing.

RUST-1870: OIDC Spec Cleanup

---

src/action/bulk_write.rs

Got a user question about this so it seemed worth documenting in addition to the error.

minor: document required server version for bulk write

---

src/test/spec/json/load-balancers/sdam-error-handling.json
src/test/spec/json/load-balancers/sdam-error-handling.yml
src/test/spec/json/server-discovery-and-monitoring/unified/hello-command-error.json
src/test/spec/json/server-discovery-and-monitoring/unified/hello-command-error.yml
src/test/spec/json/server-discovery-and-monitoring/unified/hello-network-error.json
src/test/spec/json/server-discovery-and-monitoring/unified/hello-network-error.yml
src/test/spec/json/server-discovery-and-monitoring/unified/interruptInUse-pool-clear.json
src/test/spec/json/server-discovery-and-monitoring/unified/interruptInUse-pool-clear.yml
src/test/spec/json/server-discovery-and-monitoring/unified/minPoolSize-error.json
src/test/spec/json/server-discovery-and-monitoring/unified/minPoolSize-error.yml

RUST-1930
Just a test file sync.

RUST-1930 Update tests to run on pre-4.9 servers

---

docs/tour.md

With Jada joining us next week, I put together some notes for a walkthrough of some of the driver code.  Thought it might be useful to have it checked in although I'm not sure about that; even if not, I'd appreciate your eyeballs on it to make sure I didn't get anything egregiously wrong :)

minor: add code walkthrough notes

---

src/test/spec/json/connection-string/valid-unix_socket-absolute.json
src/test/spec/json/connection-string/valid-unix_socket-absolute.yml
src/test/spec/json/connection-string/valid-unix_socket-relative.json
src/test/spec/json/connection-string/valid-unix_socket-relative.yml

[RUST-1801](https://jira.mongodb.org/browse/RUST-1801)

RUST-1801: Add spec tests for UNIX domain socket case sensitivity

---

src/test/spec/faas.rs

RUST-2000
This adds a test that, when both are present, both FaaS and container metadata are sent in the handshake.  Happily, this turned out to already be the case in the driver logic, we just didn't have the test for it :)

RUST-2000 Test that both FaaS and container metadata are recorded

---

Cargo.toml
README.md
macros/Cargo.toml
src/lib.rs

release v3.2.0

---

src/runtime/tls_openssl.rs

RUST-2144 Remove use of deprecated `openssl_probe` method

---

.evergreen/compile-only.sh

RUST-2143 Test compiling with no default features enabled

---

.evergreen/compile-only.sh
Cargo.toml
README.md
macros/Cargo.toml
src/lib.rs
src/runtime/tls_openssl.rs
src/srv.rs

I don't think including the cherry picks in this commit should be an issue, but I can pull them out into a separate PR if preferred.

release v3.2.1

---

src/runtime/tls_openssl.rs

HELP-70689
Cherrypick of #3de1b74.

HELP-70689/cherrypick

---

.evergreen/config.yml
.evergreen/run-tests.sh

RUST-2159
Will revert patchable change etc.

RUST-2159 Fix evergreen windows openssl config

---

src/client/options.rs
src/sdam/description/server.rs
src/sdam/test.rs

HELP-68823 Fix invalid_me comparison and normalize host strings (#1319)

---

Cargo.toml
src/selection_criteria.rs
src/test/spec/trace.rs
src/test/spec/unified_runner/test_file.rs

RUST-2167 Deprecate hedged reads

---

src/action/distinct.rs
src/coll/options.rs
src/test/spec/json/crud/unified/distinct-hint.json
src/test/spec/json/crud/unified/distinct-hint.yml

RUST-2087 Add hint option to distinct

---

src/action/count.rs

RUST-2081 Document filter restrictions for `count_documents`

---

src/test/spec/transactions.rs

RUST-2085 Ensure write concern options are ignored inside a transaction

---

src/test/csfle.rs
src/test/csfle/prose.rs

RUST-2206
A few of the test cases that were updated in this ticket were just missing in our suite, so I added them.

RUST-2206 Fix potential timeouts in CSE tests

---

README.md
src/client/auth.rs
src/client/auth/oidc.rs

Documents the `gcp-oidc` and `azure-oidc` feature flags and adds a better error message when they're not enabled.

Document OIDC feature flags

---

.evergreen/config.yml

I expect there isn't much value in running this task on PRs.

minor: make happy eyeballs task non-patchable

---

Cargo.lock
Cargo.toml
README.md
macros/Cargo.toml
src/lib.rs

release v3.2.5

---

src/test/spec/json/transactions/legacy-test-format.md

- Link to legacy command monitoring spec tests runner in transactions test README.rst.
- The test files are already up to date.

RUST-1671 fle2v2-CreateCollection tests expect embedded nulls to be treated specially
